### ISSUE TITLE
Fleet code forecast is not current

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#10]
The analysis appears to be getting current data but the 24hr forecast options is getting the same data which is not related to the current date.

**Comment by dominiquehausser** [comment]
I believe the problem is NOAA side, as the same problem appear downloading the data via Opencpn (the IAC fleetcode plugin in independant from zyGrib service).

**Comment by norulz** [comment]
IAC fleet codes are no longer worth the effort . Only two are currently being published. 
We need to consider removing this function and replacing it with direct download of weather fax charts that are also low bandwidth items.

**Comment by norulz** [comment]
Help needed to totally remove this and clean up the code.

**Comment by norulz** [comment]
New duplicate issue opened. Closing this one.
