### ISSUE TITLE
BUG : Modification of graphical parameters : no effect

### ISSUE THREAD

**Issue by dominiquehausser** [opengribs/XyGrib#101]
Discover by Tropelio and mentionned in the forum (https://opengribs.org/fr/forum/xygrib-support/46-some-minor-problems-with-version-1-1-1#167).

I confirm the bug (no effect for me as well).

**Comment by norulz** [comment]
Merged with [104](https://github.com/opengribs/XyGrib/issues/104)

Sorry, I did not notice this had already been opened
