### ISSUE TITLE
BUG : Problem on install data folder on Linux

### ISSUE THREAD

**Issue by dominiquehausser** [opengribs/XyGrib#103]
Problem with the XyGrib_linux_Online_Installer to install data.

[50910] Created critical message box "installationError": "Erreur", "Cannot open file \"/home/georges/Téléchargements/XyGrib_Linux_Online_Installer\" for reading: Erreur inconnue"

see https://opengribs.org/media/kunena/attachments/610/InstallationLog.txt for complete log of installation of Pancrace, signaling the problem (https://opengribs.org/fr/forum/xygrib-support/45-installation-online-echec)

**Comment by norulz** [comment]
Can anyone recreate this one?
The installer itself on Linux on most distros needs to have the executable bit set "chmod a+x".
Also the installer should ask for sudo rights. Did this occur with the particular report?

**Comment by dominiquehausser** [comment]
I do not have the problem (nor on 17.10 or 18.04LTS), but as it was another distro I open the bug to be sure we check that (as I was unable to understand the problem reading the log file

**Comment by norulz** [comment]
fixed in 1.1.2
