### ISSUE TITLE
Pressure H and L markings with Arpege and ICON need to be smoothed

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#105]
There is a big difference between the High and Low markings  when the grib is from GFS versus a grib from Arpege or ICON.

This is most likely due to the fact that PRMSL in GFS is smoothed while in the others it is not.
The original code is good for GFS but needs to be modified to create less clutter with the L & H markings

**Comment by did-g** [comment]
Hi,
In my understanding L & H didn't really work with GFS either.
With:
1 1 1
1 2 1
1 1 1
2 is a high
but with 
1 1 1
1 2 1
1 2 1
1 1 1
it's not

**Comment by norulz** [comment]
I'm looking for a better algorithm. It should also take into account a step of about 4-5 mb difference before declaring a local high or low.
Do you have any ideas?

**Comment by norulz** [comment]
hi @did-g ,
I have done some trials and feel that there are 2 main options
**First is to use a better algorithm for finding maxima and minima in a **noisy** 2D array**
I found some applicable links via a [google search](https://www.google.co.il/search?rlz=1C1CHZL_enIL755IL755&biw=1659&bih=882&ei=RTWvW4LbDcapsgGc2KaABw&q=find+maxima+and+minima+in+2d+array+with+noisy+data&oq=find+maxima+and+minima+in+2d+array+with+noisy+data&gs_l=psy-ab.12...9569.10997.0.13757.5.5.0.0.0.0.172.807.0j5.5.0....0...1c.1.64.psy-ab..0.1.162...33i10k1.0.uNxHYfPp7vI)
This [perl routine](https://www.perlmonks.org/?node_id=800691) might be worth porting 

**Second option might be to smooth the PRMSL data at file load time**
This might be into a separate record type (i.e. PRMSL2) which we use only for the H/L routine or we might as well display the smoothed data as PRMSL providing the user a less noisy synoptic map. True that it somewhat changes the original data. If GFS feels free to do it why can't we?

Here are the results of showing raw Arpege PRMSL with H/L set on and the other image shows the same data after running a 9 point smooth routine.
![image](https://user-images.githubusercontent.com/6072089/46243267-05f50d00-c3db-11e8-80e7-45792eac86fa.png)


![image](https://user-images.githubusercontent.com/6072089/46243273-2624cc00-c3db-11e8-9616-c5992027b105.png)

**Comment by dominiquehausser** [comment]
In the smoothed image, L is lost even it is obvious most L present in the first image should be present in the 2nd one.

I am not coming into the discussion on the technical computing aspect, but more in the perspective of the user of data who visualise them to get the best forecast as possible, based on these RAW data and I am not really happy with the second image.

XyGrib is visualing RAW data provided by the centers running the models and if data started to be modified to improve visualisation without changing the interpretation of the raw data, no problem, but if that's modify even potentialy interpretation, I am not sure it's a good idea, specially as we know a lot o people are taking output as the reality (without remembering, even if it is repeated everywhere, that this is not expertised forecast.

I have been looking on large scale (Pacific from Equateur to South and Atlantic from Equateur to North, what is shown on the 3 models, as we could imagine the number of H or L appears particularly in area with very low gradient of pressure (quite .

To smooth these data (I generally do not use this parameter, as I do not smooth color or numerical data interpolation), what will be the criteria to choose the "best place" of H or L in the low gradient area and be sure, when it is obvious that they do not disapear ?
![hl_3modelspacific100](https://user-images.githubusercontent.com/38014738/46245301-e0243400-c3eb-11e8-956b-139de824de10.jpeg)
![hl_3modelspacific50](https://user-images.githubusercontent.com/38014738/46245302-e0243400-c3eb-11e8-9a61-1e41a86333b8.jpeg)
![hl_3modelsatlantic100](https://user-images.githubusercontent.com/38014738/46245303-e0bcca80-c3eb-11e8-96b3-dc4d979310be.jpeg)
![hl_arpegeglobalatlantic](https://user-images.githubusercontent.com/38014738/46245304-e0bcca80-c3eb-11e8-8872-34997dd8ee1d.jpeg)
![hl_dwdiconatlantic](https://user-images.githubusercontent.com/38014738/46245305-e0bcca80-c3eb-11e8-9481-d9c4ded35856.jpeg)
![hl_gfsatlantic](https://user-images.githubusercontent.com/38014738/46245306-e0bcca80-c3eb-11e8-897a-cebe6c9aef09.jpeg)
![hl_gfspacific](https://user-images.githubusercontent.com/38014738/46245307-e0bcca80-c3eb-11e8-93c1-64956009d414.jpeg)
![hl_dwdiconpacific](https://user-images.githubusercontent.com/38014738/46245308-e1556100-c3eb-11e8-831c-aea22ab9913e.jpeg)
![hl_arpegeglobalpacific](https://user-images.githubusercontent.com/38014738/46245309-e1556100-c3eb-11e8-9ab4-07f8e7b15372.jpeg)

**Comment by did-g** [comment]
Hi,
L missing is likely an implementation bug.

Smoothing can help for H and L but I'm not sure displaying smoothed MSL is a good idea.

What about 'deep learning'? half joking weather faxes are produced from GFS..., or using some kind of pattern recognition with isobar curvature and wind direction.

**Comment by norulz** [comment]
I agree that the smoothing needs to be at the process that extracts H/L and not the source data.
There is machine learning stuff out there that can recognize synoptic patterns but I suggest we first try some algorithm for maxima and minima in a a noisy 2D array.

**Comment by dominiquehausser** [comment]
I am in contact with a team in CH working on this kind of problems  and hoping they have a good idea (https://models.slf.ch/p/meteoio / https://models.slf.ch) to help us to solve this question/problem.

**Comment by norulz** [comment]
Great!

**Comment by did-g** [comment]
https://www.adv-sci-res.net/4/105/2010/asr-4-105-2010.pdf

**Comment by norulz** [comment]
I have done a simple fix that appears to be OK. It not shows only the absolute maxima or minima in each quarter of the grid. No more than 4 H's or 4 L's can be shown. (Less is possible). However the ones that are shown are the local max.

@did-g @dominiquehausser - please test and see if we have a solution.

**Comment by dominiquehausser** [comment]
Quite good.
See images 1. ICON before 2. ICON after 3. GFS 
![hl](https://user-images.githubusercontent.com/38014738/48351168-b6685900-e689-11e8-9702-dba67e247f78.jpeg)
![hl1](https://user-images.githubusercontent.com/38014738/48351175-ba947680-e689-11e8-8039-fa5348abdadf.jpeg)
![gfs_hl2](https://user-images.githubusercontent.com/38014738/48351180-be27fd80-e689-11e8-91ec-03bd683a36bf.jpeg)

**Comment by did-g** [comment]
Hi,
looks great cf vs NOAA fax.
http://tgftp.nws.noaa.gov/fax/marine.shtml

**Comment by norulz** [comment]
Great!
Closing this issue
