### ISSUE TITLE
Unicode characters in appdata paths

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#108]
We need to handle unicode (utf-8) characters in paths leading to user appdata locations. The users name will be in many cases in non lower ascii characters

**Comment by norulz** [comment]
I have not yet found a Linux distro that lets me create a user with an extended character in the name!
This may not be an issue.

**Comment by dominiquehausser** [comment]
in Ubuntu the command line sudo useradd allow to do it, but not sudo adduser

**Comment by norulz** [comment]
On my 18.04 with gnome it does not
```
david@david-VirtualBox:~/qtprojects/xygrib$ sudo adduser jörgen
[sudo] password for david: 
adduser: To avoid problems, the username should consist only of
letters, digits, underscores, periods, at signs and dashes, and not start with
a dash (as defined by IEEE Std 1003.1-2001). For compatibility with Samba
machine accounts $ is also supported at the end of the username
david@david-VirtualBox:~/qtprojects/xygrib$ 
```

**Comment by norulz** [comment]
Fixed. Will be in next release (1.2.6)
