### ISSUE TITLE
Loading gribs

### ISSUE THREAD

**Issue by dapique** [opengribs/XyGrib#111]
It doesn't load ICON gribs downloaded from DWD's ftp. If I use the download assistant there is no problem.  Could anybody tell something about how the download-grib tool works? I mean, my first thought is that before show the data inside the grib, there is a conversion from triangular to regular (lon/lat) grid, but I'm not sure.

Greetings.

David.

**Comment by norulz** [comment]
Hello David
The ICON Global model uses a Icosahedral (triangular) grid. Most grib readers including XyGrib don't handle this grid form. We therefore perform a re-projection of the ICON data before placing it on our Grib Server.
We do aim to make XyGrib as open as possible to all grib grids. In time we will get there.
Thanks,
David
