### ISSUE TITLE
Problems with ver 1.1.1 on Mac

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#114]
@nohal hi,

Can you please take a look at this post on the forum. A user is having problems with the new version on his Mac.

[https://opengribs.org/en/forum/xygrib-support/50-ver-1-1-1-not-working-on-mac#199](https://opengribs.org/en/forum/xygrib-support/50-ver-1-1-1-not-working-on-mac#199)

**Comment by norulz** [comment]
Appears to be missing the PROJ library.

**Comment by nohal** [comment]
If a library was missing, the application would not start at all, exactly the same as if you remove a required .dll on windows or .so on linux...
Proj is part of the system on macOS, so we do not distribute it at all:

```
$ otool -L /Applications/XyGrib/XyGrib.app/Contents/MacOS/XyGrib
/Applications/XyGrib/XyGrib.app/Contents/MacOS/XyGrib:
	@executable_path/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.11.0, current version 5.11.2)
	@executable_path/../Frameworks/QtXml.framework/Versions/5/QtXml (compatibility version 5.11.0, current version 5.11.2)
	@executable_path/../Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport (compatibility version 5.11.0, current version 5.11.2)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/Library/Frameworks/PROJ.framework/Versions/4B/PROJ (compatibility version 13.0.0, current version 13.0.0)
	@executable_path/../Frameworks/libpng16.16.dylib (compatibility version 52.0.0, current version 52.0.0)
	@executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.11.0, current version 5.11.2)
	@executable_path/../Frameworks/QtGui.framework/Versions/5/QtGui (compatibility version 5.11.0, current version 5.11.2)
	@executable_path/../Frameworks/QtCore.framework/Versions/5/QtCore (compatibility version 5.11.0, current version 5.11.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

From the symptoms it's hard to say what happens - the last zyGrib behaved exactly like this on macOS, but I was convinced this is fixed in XyGrib.

Maybe it's time to implement some logging :)

**Comment by norulz** [comment]
I can replicate the problem on a fresh install of os x 10.13.6 (High Sierra).
The message is the same.

**Comment by nohal** [comment]
Please check https://spideroak.com/storage/NZXWQYLM/shared/1092636-2-1053/XyGrib-mac-1.1.1.pkg?b771db4f2123e0f4d7a83f2a89c83e5d and let me know if it solves the issue for you and does not introduce some other. It uses the obvious workaround of forcing the build against newer proj.4 from Homebrew and bundling it with the application.

**Comment by norulz** [comment]
Yes - Library/Frameworks is on the machine I tried.

I checked the new pkg and it install and runs OK on a completely fresh VM machine using OS X 10.13.6

Thanks @nohal
