### ISSUE TITLE
West of Longitude 0 selected download area grows on subsequent downloads

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#117]
If an area selected for download is west of longitude 0, subsequent downloads (based on rectangle of current grib) cause the area to grow. East of Lon 0 there seems to be no problem.

**Comment by did-g** [comment]
Hi,
I can't reproduce it on Linux or I don't understand the issue, could you attach a screenshot?

Thanks
Didier

**Comment by norulz** [comment]
Hi,
It does not reproduce on Linux or on Mac. 

On Windows it always occurs in one case only - If 'Longitude min' is west of lon 0 **AND** 'Longitude max' is east of lon 0. 
In this case each subsequent download changes Longitude min 1 degree westward.
I'm setup on Windows as well so I'll take a look at the code.

**Comment by norulz** [comment]
Hi,
I'm attaching the libraries that were built using mingw/msys on one windows machine. The build setup is on a second machine with Qt 5.11 using the mingw32 tool kit. I separated as msys was causing conflicts with the windows git setup and the Qt installation does not include msys.

I suggest selecting only one toolkit - mingw32.  CMake does't find all the libraries so I manually point to them in the build setup facility of qtCreator.

The bug appears to be related to the several times that the rectangle coordinates go through  ceiling/floor functions.


[dev.zip](https://github.com/opengribs/XyGrib/files/2471905/dev.zip)

**Comment by norulz** [comment]
BTW the setup won't run XyGrib until openjpeg2.dll is copied to the build folder where the XyGrib.exe file is

**Comment by norulz** [comment]
The bug can be replicated in release build but not in debug build.

**Comment by norulz** [comment]
This issue raises a valid question:

Why do we need to set the rectangle of the grib request to the outer whole degree?
The grib server can handle fractional degrees in decimal form
What is wrong with requesting a rectangle with fractional degrees in decimal form? 
We do mange the rectangle in doubles after all.

What do you think?

**Comment by did-g** [comment]
Hi,
Likely either 
- older servers couldn't 
- saildoc 
- it's a decimal issue the . , things?
- have to convert between decimal and degrees / minutes.
- bigger input areas
- no reason

**Comment by norulz** [comment]
Hi Didier,

Take a look at my commit from a few minutes ago and try in on any platform.
There is no conversions required. The rectangle that the user requests is passed on without any change in size to the grib server.
The grib server will adjust slightly according to the model resolution. 0.25 deg will be on the closest 0.25 and an 0.5 deg model will be in the closes 0.5.
I see no reason why not to keep this. It has nothing to do with saildocs etc.
In the original system the user was getting bigger gribs than requested. Now the user gets much more closely what he or she requested.

I also know the source of the bug. The dialog spinners that hold the coordinates hold this in doubles. In the Windows OS there is obviously a very small decimal value that triggers the floor function to move to the next degree when the value is minus (west of lon 0)

**Comment by did-g** [comment]
Hi,
On linux with french language:
cosmetic but mode resolution is 0.25 0.5 1.0 but min/max is: -123,10 5,2
downloading return a server error 'bad request'

**Comment by norulz** [comment]
The git version is currently running without the round up to nearest degree in the area selector. This is perhaps better for the higher resolution Gribs about to be added.

Closing the issue

**Comment by did-g** [comment]
Could you double check on your setup with a locale using ',' for decimal?
Here with french download dialog compute the wrong size and the server return an error.

Thanks

**Comment by norulz** [comment]
Hi,
In Windows it is not connected to the computer locale but only to the language selected in XyGrib.
Interesting is that the change of decimal indicator does not change in the status bar at the bottom or in the weather-board on the left but it does in input widgets.

There must be an elegant Qt solution. I'll start looking

**Comment by norulz** [comment]
This seems to fix the issue, Still testing
```
//-------------------------------------------------------------------------------
void DialogLoadGRIB::updateParameters ()
{
    double tmp, xm, ym;
    
//    ymax = sbNorth->cleanText().toDouble();
//    ymin = sbSouth->cleanText().toDouble();
//    xmin = sbWest->cleanText().toDouble();
//    xmax = sbEast->cleanText().toDouble();


    QLocale l =  QLocale();
    ymax = l.toDouble(sbNorth->cleanText());
    ymin = l.toDouble(sbSouth->cleanText());
    xmin = l.toDouble(sbWest->cleanText());
    xmax = l.toDouble(sbEast->cleanText());
```

**Comment by norulz** [comment]
Solved by removing the roundup to ceiling.
