### ISSUE TITLE
Need to be able to read Gribs with Lambert conformal projection

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#118]
The NOAA NAM coverage for CONUS uses a non lat/lon grid.
We need to be able to read this.

**Comment by did-g** [comment]
Hi any sample of mercator grid? There's NOAA blend but it's a category 6, xygrib doesn't understand it.
I have some but on a different computer, thousand miles away..., likely current or wave.

**Comment by did-g** [comment]
Thanks a lot, never mind, as usual just after posting I found an old NDFD oceanic mercator one.

**Comment by norulz** [comment]
I would need to dig deep into what libproj can provide us. I suspect that the solution should be there.
It might be worth taking a look at how wgrib2 creates a new grid. (That's what I'm using for the pre-processed grid change for NAM-CONUS).

**Comment by did-g** [comment]
IIRC wgrib2, degrib and so on are using pre-computed tables for grid to lat
/ lon conversion, if you want to support unstructured grids you have to
anyway and it's likely faster. Others are using something like Xygrib
map2screen/ screen2map,

**Comment by dominiquehausser** [comment]
Hello,
I do not know if it helps in the discussion.
https://proj4.org is the project that allow to convert any projection to any others. This is what is used by the GIS world.
This is the libraries I was using when running spatial statistical analysis with the tool R-Project (https://www.r-project.org). As a user, not a real developper.
I will try to find (again) the formula for this transformation Lambert conical to Mercator.

**Comment by did-g** [comment]
@dominiquehausser libproj being proj4.org if you still have proj4 init around would be nice but don't spend to much time on it.
