### ISSUE TITLE
Some display issues with altitude data

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#119]
Attached is a file with some ECMWF altitude data. It also has PRESS at MSL which needs the current git commit to show (1.1.2 does not show PRESS at MSL only PRMSL at MSL)

(BTW I'm inclined to add ECMWF free altitude data on a bi daily basis to the Grib server. There is no surface data except PRESS but it has value for general forecasting several days ahead)

While trying this free source out I noticed some problems

- With altitude 850mb chosen and Temperature coloring selected the coloring does not work. This does work for wind at 850mb.
- With altitude 850mb chosen wind arrows do not display unless wind coloring is selected
- Temp at 10m option is not grayed out although temp at 10m is not part of the file

[ecmwf_small_sample.zip](https://github.com/opengribs/XyGrib/files/2472968/ecmwf_small_sample.zip)

**Comment by did-g** [comment]
For temperature what should it do? Currently it's temperature at 2 m (not always).

**Comment by norulz** [comment]
If you load the ecmwf file that does not include temp at 10m but only temp at lever 850 hpa the option to display the temp numbers at 10m in the "Weather" menu should be disabled.

The option higher in the menu to show the color overlay for temp should be active if the 850 hpa level has been selected
