### ISSUE TITLE
v1.1.2 French language file causes page up/down keys not to work on Windows

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#120]
I was able to replicate this on Windows with French set as the language in XyGrib.
Reverting to previous qm file fixed the problem.
There must be some corruption in the language file.

**Comment by dominiquehausser** [comment]
same problem on linux. When back home I'll check differences.

**Comment by dominiquehausser** [comment]
OK corrected. There was a couple of translation where some punctations were missing at the end.
Disappeared when doing the cleaning of the french translation. I put them back.

**Comment by norulz** [comment]
Recompiled files fixed the issue.

**Comment by dominiquehausser** [comment]
I must be very stupid, but no, it is not working in french, it work in other languages.

To be sure I download the latest files from https://github.com/opengribs/XyGrib/tree/master/data/tr and put them directly in my data repository.

I recompile the app on 2 differents machines with the same result.

I compare these files with the ones I have in my local git folder they are exactly the same.

I have no idea what do you mean by recompiled as .qm files are created by qtlinguist fro .ts files. So I have no idea what is wrong and how to correct it.

Thanks in advance for your help

**Comment by norulz** [comment]
The recompile I mentioned is not the application recompile but the running of "lrelease" on the French .tr file to create an updated .qm file.

The French .qm file in the 1.1.2 distribution is the source of the problem. All I did to fix it was to run lrelease on the French .tr file and the new .qm file was placed in the tr folder.

The qm file in the 1.1.2 release came from a PR that you created. If you are now seeing the same bug then there is something wrong with the creation of .qm files on your machine.

**Comment by dominiquehausser** [comment]
OK, I have check that also GUI (linguist version 5.9.5) and command line (lupdate, linguist, lrelease) to get potentiel error message. Nothing, so I do not understand what's wrong.

**Comment by norulz** [comment]
Hi, Do I understand correctly that you still have the bug and that the pgup and pgdn keys are not working with the French language file active?

If so please try and use the .qm file that I uploaded to the [forum](https://opengribs.org/media/kunena/attachments/524/xyGrib_fr.zip) and see if it fixes the problem.

If it does, then we can be sure that the issue is local to your Qt version or machine. 

I am using Qt 5.11. I also create the .qm files via QtCreator by going to the projects screen (with release selected) and I change the setting of the Build Steps from "all" to "translations" and then I activate the build. Any new .tr files will then generate new .qm files. Choosing "translations_update" apparently creates new .ts files if neeeded.

**Comment by dominiquehausser** [comment]
Does not work with the xyGrib_fr.qm in the master tree.

I went back to older releases : OK with release-v1.1.1-final, but not after.

I do not understand what has changed as I have always use the same tool and compile all language. I cannot see any error message whith some translation, maybe a hidden character somewhere.

**Comment by norulz** [comment]
Hi Dominique,
I took the fr.ts file from ver 1.1.1 and generated a new fr.qm file based on it. It works fine.
I therefore also feel that there is something bad in the newer fr.tr file. I will try and find the problem and in the worst case you may need to re-translate the delta from the previous version.

**Comment by norulz** [comment]
I ran a diff on the two .tr files (the good one and the bad one) and found that the problem may be connected to the removal of obsolete tags. The file with obsolete tags removed is the one that is causing the problem.
I suggest not to use this option until we learn more.

**Comment by dominiquehausser** [comment]
With the old qm file this is OK again after my last build after commit 362 (with the new models). I will rapidly try to add the new translation again, so we have a correct french translation before publishing the upgrade with the new models.

**Comment by dominiquehausser** [comment]
Problem solved. I translated PgUp as page précédente and PgDn as page suivante (without realising it was a key command.
I had nothing to do with noobsolete as I removed all obsoloete translation in all languages.
I'll create a pull request, with the new french translated .ts and .qm
