### ISSUE TITLE
We need to automate language builds in CMake

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#121]
Since the move from Qmake .pro file to CMake we lost the automation of building the language files using lupdate and lrelease.

@nohal can you kindly help out on this?

**Comment by dominiquehausser** [comment]
I must be very stupid but build does not work anymore.

cmake -DCMAKE_INSTALL_PREFIX=$DefaultInstallDir ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PROJ4: /usr/lib/x86_64-linux-gnu/libproj.so  
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
CMake Warning at data/tr/CMakeLists.txt:3 (FIND_PACKAGE):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


CMake Error at data/tr/CMakeLists.txt:8 (qt5_create_translation):
  Unknown CMake command "qt5_create_translation".


-- Configuring incomplete, errors occurred!
See also "/home/dominique/0_Data/dev/XyGrib/build/CMakeFiles/CMakeOutput.log".
[CMakeOutput.log](https://github.com/opengribs/XyGrib/files/2476616/CMakeOutput.log)

**Comment by did-g** [comment]
Hi
you have to install:
qttools5-dev
for example on a recent debian
sudo apt install  qttools5-dev

**Comment by norulz** [comment]
@dominiquehausser  hi,

You can duplicate the prerequisites from the .travis.yml file for Trusty.
There has been a change in the "sudo apt-get install ..." line in that file to ensure the language build tools are available.

The new additions to the cmake system now make it extremely easy and robust to initiate language file updates and language compiles via the build commands selector in Qtcreator.

**Comment by dominiquehausser** [comment]
OK. Thanks

**Comment by dominiquehausser** [comment]
In automation, '-noobsolete' should be add to suppress the expressions that are no more used in the code.

**Comment by norulz** [comment]
I'll check on how to add it
