### ISSUE TITLE
Coverity and appveyor

### ISSUE THREAD

**Issue by did-g** [opengribs/XyGrib#124]
Hi,
Could you create accounts with coverity and appveyor for CI?

I have one with coverity but it returns 'Last Build Status: Failed' since September the 28 and they don't reply mail request, maybe because mine is a fork.

Regards
Didier

**Comment by norulz** [comment]
I registered with both.
Please advise on anything else that I need to do.

**Comment by did-g** [comment]
Did you register opengrib/FXyGrib with:
https://scan.coverity.com/projects/new?tab=github_index

if not I will do.

**Comment by norulz** [comment]
I have registered the project but the configuration is not complete. I tried but got lost!
Perhaps you can get it running.

**Comment by did-g** [comment]
For coverity you have to wait until they send you a mail.
I'm looking in appveyor stuff but we'll need some storage for libraries,
may a new project under opengribs? And maybe another project for grib test
data

**Comment by did-g** [comment]
Hi,
managed to compile on appveyor at last.
We need a place for storing missing libraries and include files, either on
github in a new project or on your site,
BTW openjpeg is compiled as shared dll and it's missing in your tarball.
Currently it's only compilation there's no installer.

Then we can enable appveyor on PR.

No news from coverity? Looks like they are one their way out...

Regards
Didier

**Comment by norulz** [comment]
Hi Didier,
I have given you member rights on the opengribs git organization. The allows you to create new repositories. Feel free to setup a repository for the files needed.
