### ISSUE TITLE
missing files and wrong paths in debian package 

### ISSUE THREAD

**Issue by dangowrt** [opengribs/XyGrib#128]
Trying to build the Debian package for the v1.1.2 release. Build works, but changelog is still on v1.1.1 (easy to fix, obviously). However, the resulting binary looks for all data files in wrong locations, it seems that the patching the paths resulted in wrong absolute paths (ie. `/usr/share/xygrib/` prefix is missing, according to strace the binary tries to open absolute paths like `/data/img/cursor-cross.png` instead of `/usr/share/data/img/cursor-cross.png`).
Also maps are installed in `/usr/share/maps` instead of `/usr/share/xygrib/maps`, `fonts`, `gis`, `img` and `tr` is missing entirely and just not packaged.
@free-x please help, it'd be a great help to use XyGrib in future SAR missions on the Mediterranean, for that we use Ansible to setup Debian machines (hence a binary installer would mess up our efforts towards automation and reproducible builds, apart from that also the binary installer ended up with missing icons).

**Comment by dominiquehausser** [comment]
Hello,
Have a look on the script here : https://github.com/dominiquehausser/XyGrib/releases/tag/v1.1.1, which help to install application and data were you wish. It works well  with Ubuntu.

**Comment by dangowrt** [comment]
@dominiquehausser thanks a lot. I'll have a look at it. The problem is that conducting a local build on each target device is not an option here, we need reproducible debian packages for several (procedural, maintainability, security, ...) reasons. ie. generating a debian package using `dpkg-buildpackage -b` would be the way already started by @free-x with only few problems which need to be addressed.

**Comment by free-x** [comment]
Hi,

sorry for delay ... 
actually, that doesn't fit anymore. I've already adapted in my private repository but haven't pushed yet. I still have a small problem when installing package on Mint 19. I don't understand why the same package works without problems on Ubuntu 18.04 but not on Mint 19 which is based on the same 18.04 :-(

**Comment by dangowrt** [comment]
I don't mind either ubuntu nor mint, as long as it works on Debian which should also be the reference case for everyone downstream building upon that, so imho the best place to start.
Can you push the updated debian packaging for v1.1.2 or share you private tree here on github?

**Comment by free-x** [comment]
@dangowrt 
what arch platform do you package for? i386? amd64? armhf?

**Comment by dominiquehausser** [comment]
@free-x : for Raspberry Pi, 32bit is still needed.

**Comment by dominiquehausser** [comment]
@free-x  There are many users of Raspberry Pi and it would be nice to give them an package. There is still quite some work to put then the app ready for use on the ssd card of the Raspberry.
If I can avoid to do it wrongly myself, it is better to have a package in the way described by @dangowrt

**Comment by free-x** [comment]
Hi guys,

I'm so sorry. But 1.1.2 But it seems that with 1.1.2 will probably be nothing
I don't understand how and where XyGrib search /data and /maps
I have tried classical installtion ( s. https://github.com/opengribs/XyGrib/blob/master/INSTALL.md)
After "sudo make install", I have my binary /usr/local/XyGrib/XyGrib and data in /usr/local/XyGrib/data
Now I'm trying folowing 
```strace /usr/local/XyGrib/XyGrib 2>&1 | grep maps```
And notice that the maps are being searched elsewhere.
```
Could anybody assist me to try same and post your output here?

**Comment by dominiquehausser** [comment]
My binary is /usr/local/bin/XyGrib and my data are located to /usr/local/share/openGribs/XyGrib/data.

It is build using the following script (see attach file).

`strace /usr/local/XyGrib/XyGrib 2>&1 | grep maps` give me plenty of lines (I show just the first one):
[Xygrib_newbuild.sh.txt](https://github.com/opengribs/XyGrib/files/2486991/Xygrib_newbuild.sh.txt)

> stat("/usr/local/share/openGribs/XyGrib/data/maps", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0

**Comment by free-x** [comment]
Hi Guys,

It's done. I just opened PR that fixes the bugs for 1.1.2.
My branch: https://github.com/free-x/XyGrib/tree/v1.1.2-Release
Pull request:  https://github.com/opengribs/XyGrib/pull/129

@dominiquehausser I'm considering if I might organize a repository for Raspbian next week....

Thx all for assistance

Regards
free-x

P.S. @norulz You can close this issue. I'm gonna do another PR for Master Branch.

**Comment by norulz** [comment]
Thanks.

**Comment by dangowrt** [comment]
Amazing! I'll give it a shot tomorrow!

**Comment by dominiquehausser** [comment]
Thanks a lot fot.

**Comment by dominiquehausser** [comment]
@free-x :
1) Is there a way to build .deb for Pi on a VM ? or is it absolutely necessary to have a Pi "machine"?
2) Is it possible to build .deb for more than one environment without having them in VM ?

**Comment by dangowrt** [comment]
@dominiquehausser 
the easiest option is using building inside an ARMv7 or ARM64 VM. You can use debian on armv7 (for rpi and rpi2) or arm64 (for rpi3) with eg. qemu.
the more elegant option is https://wiki.debian.org/CrossCompiling

**Comment by nohal** [comment]
And all of that you get "for free" if you create a PPA at https://launchpad.net

**Comment by free-x** [comment]
@nohal 
I don't want to start flame war. But in my opinion it is not right to install the deb packages for ubuntu on a debian. Binary the packages are created with different compiler versions ( stretch: 6.3.0, xenial 5.3.1, bionic: 7.3.0) and linked against different libraries e.g. glibc ( stretch: 2.24, xenial: 2.23, bionic 2.27), qt5 (stretch 5.7.1, xenial 5.5.1, bionic 5.9.5). That is also the reason why I recompile the OpenCPN for myself for stretch
Unfortunately Launchpad does not provide support for native debian

**Comment by nohal** [comment]
OK, so are you ready to maintain all the Debian ARM builders? I am definitely not. What exactly is not working in OpenCPN that you have to recompile it?

**Comment by free-x** [comment]
@nohal 

> OK, so are you ready to maintain all the Debian ARM builders?
Not sure, what do you mean

>What exactly is not working in OpenCPN that you have to recompile it?
I didn't start it at all because of the above mentioned reasons :-) Therefore no judgement what runs or does not run. If everything goes well, I'm happy for you.

No war, make fun

**Comment by nohal** [comment]
> @nohal
> 
> > OK, so are you ready to maintain all the Debian ARM builders?
> 
> Not sure, what do you mean

Someone has to maintain the builders for all the Debian releases, no? It is simpler with the chroots now then it was when we needed (virtual) machines, but someone still needs to do it.

> 
> > What exactly is not working in OpenCPN that you have to recompile it?
> 
> I didn't start it at all because of the above mentioned reasons :-) Therefore no judgement what runs or does not run. If everything goes well, I'm happy for you.
> 
> No war, make fun

No war intended, I was just curious as all the packages from all the PPAs work for me across all debian releases I have been using over the years (I am no using Debian past Jessie though so would like to know if this changed with Stretch and understood your comment as suggesting you know there are problems).

**Comment by dangowrt** [comment]
The easiest solution would obviously be to just submit the package to upstream Debian. License allows that, so what is preventing you from enjoying Debian's existing build infrastructure? Maybe @lynxis can help out in case there are difficulties or questions with regard to how to have it included.
Because that'd solve all these issues in the long-term, ie. once the package is included in Debian main (nothing I can see should technically prevent that) it will more or less automatically find it's way into Ubuntu, Mint, Raspbian and all the other Debian-based distros.

**Comment by nohal** [comment]
That of course is the way to go, shall there be someone willing to become the maintainer in debian.

**Comment by free-x** [comment]
ping @norulz @dominiquehausser 

Moin,

what lasts for a long time also resists for a long time.... As I promised, I have organized Debian repository. There are packages for AMD64 & ARMHF on Debian Buster

Small HOWTO
```
wget -O - https://www.free-x.de/debian/oss.boating.gpg.key  | sudo apt-key add - 
sudo vi /etc/apt/sources.list.d/oss.list
deb https://www.free-x.de/debian/ buster main contrib non-free
sudo apt update
sudo apt install xygrib
```
Have a fun
Regards
free-x
