### ISSUE TITLE
"Offline" installers actually download the software from the internet

### ISSUE THREAD

**Issue by caesar** [opengribs/XyGrib#135]
I installed XyGrib 1.1.2 on both macOS and Windows using the offline installers. (I like to have offline installers for all my software saved in case I need to reinstall at sea or in a remote area.)

**Bug:** On both systems, the installer actually downloaded the software over the network.

**Expected behaviour:** The offline installers should be self-contained and not use the network. (Unless the optional high-resolution imagery is selected, I guess).

XyGrib version: 1.1.2
Platfom: Windows 10 (1810) and macOS Mojave (10.14.1)

PS – Great to see development of zyGrib resumed, and in the open. :+1: Hopefully I'll get a chance to contribute.

**Comment by norulz** [comment]
Hi caesar,

This is intended behavior. If an internet connection is available at installation time the "offline" installer will prefer the files in the online repository over those in the installer payload. This insures installation of the latest model.

Should there be no connection the files are taken from the installer payload.

You are welcome to join in and contribute. The whole idea is to make this a community effort.

**Comment by caesar** [comment]
Hi David,

Hmm, that feels strange to me given that it's labelled as an "offline" installer, but I can see the advantage in checking for the latests release in case it's newer.

My suggestion would be to check for a newer release and then if there is one, ask the user whether they want to download it or proceed with the version in the installer payload. And if there isn't a newer, obviously no need to download anything.

Alternatively, perhaps a simple option could be presented in the installer so the user can choose whether to re-download the app or use the version they've already downloaded.

At the very least perhaps a note should be added somewhere to the effect that the offline installers are actually online installers unless you disconnect from the internet. In my case, had I known, I would have disconnected – I knew I had the latest version, and the installer took nearly an hour to download it again… fortunately I'm not on a metered network at the moment, but at other times it could have been an expensive mistake.

I definitely intend to contribute as soon as I can get my build environment set up – today I don't have a good enough internet connection… 😀
