### ISSUE TITLE
XyGrib is installed globally on Windows but only works for one user

### ISSUE THREAD

**Issue by caesar** [opengribs/XyGrib#137]
**Bug:** On Windows, XyGrib is installed globally (to `C:\Program Files (x86)\`) but when it is launched by a user other than the user who ran the installer, the map imagery and the toolbar icons are not visible.

**Expected behaviour:** XyGrib should work for all users if installed globally.

XyGrib version: 1.1.2
Platform: Windows 10

Related: #136

**Comment by caesar** [comment]
Screenshot of XyGrib when launched by a user other than the one who installed it:

![xygrib no icons](https://user-images.githubusercontent.com/1566516/47610096-4750fa80-da23-11e8-9c3f-c939573146de.png)

**Comment by caesar** [comment]
Note: in zyGrib 7.0 a similar bug manifests when opening a grib file with the app from Windows Explorer, instead of from within the app. (I haven't tested this yet with XyGrib.)

**Comment by norulz** [comment]
Hi,
Right now installation puts the static data in the user folder 
C:\Users\<user>\AppData\Roaming\openGribs\XyGrib\data...

We will consider an option to install globally in a future release. In the mean time there are two possible work around's
- The folder structure for the static data can be copied from the installing user to other users
- The "data" folder structure can be copied to the executable location (where XyGrib.exe is located)

**Comment by norulz** [comment]
Merging this issue with [https://github.com/opengribs/XyGrib/issues/136](https://github.com/opengribs/XyGrib/issues/136)
and closing this one.

**Comment by caesar** [comment]
It's not really the same issue, but okay. :-)

Thanks for the tip on the workaround; I had assumed copying the data to each user's AppData folder would work, but not tried it yet.

I would suggest that a better solution for a global install would be for the data to be in `C:\ProgramData\`.
