### ISSUE TITLE
New Regional Models in Grib Server - Testing needed

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#139]
There are new additions to the grib server with corresponding updates to XyGrib code.

New Global Model - ECMWF. This is the public release with 24hrs temporal resolution, 0.5 deg spatial resolution and with only a few parameters. It is valuable mainly for looking at the general synoptic forecast a week or so ahead.

New large area regional models have been added these include 3 NAM areas at 12km (Conus, Central America & Carribean and the Pacific area around Hawai). Also new are ICON-EU nest at 0.06 degree and Arpege EU nest at 0.1 degree.

A combo has been added to the toolbar to show the regional models' coverage.

Server status dialog now shows all models. Some GUI improvement is needed here (one tab  for global models and one for regional. 1-6 and 6-12).

Please test it all out and try and get the bugs to surface.

**Comment by did-g** [comment]
Hi,
Server status dialog box is too big on a 1300x800 pts, ie OK button  is off screen.

**Comment by dominiquehausser** [comment]
Problem seen:
Arpege-EU no pressure data (if selected alone in the dowload screen : messsage of error, if other data included no error message, but no data).
Limits shown for NAM PACIFIC is the same as NAM CARBIEAN + HAWAI zone; when downloading only Hawai area is present.
When not choosing an atmospheric model, it is still possible to choose reflectivity.
On status of server date for ICON-EU is 2018-10-13 and for Arpege-EU is 2018-10-13, downloaded files are from today.

Really nice job.

**Comment by norulz** [comment]
> Server status dialog box is too big on a 1300x800 pts, ie OK button is off screen.

I know! 
If you have the time and feel like doing some GUI, a solution might be to have two tabs. The first one "Global Models" and the second "Regional Models" (first 6 and last 6 in the current list).
This would provide a dialog about half the height.

**Comment by norulz** [comment]
> Limits shown for NAM PACIFIC is the same as NAM CARBIEAN + HAWAI zone; when downloading only Hawai area is present.

@dominiquehausser - Can you attach a screen shot showing the problem.
The other bugs have been fixed and the status report for ICON-EU and Arpege-EU will update in the next cycles.

**Comment by dominiquehausser** [comment]
This morning it is OK. I may have had bad eyes yesterday evening.
I think this one is normaly called NAM-HAWAI and not NAM-PACIFIC

**Comment by did-g** [comment]
Hi,
Two tabs would be nice.
File server status is also redundant with the dialog box title, at least on
linux.
Maybe some kind of user sortable grid layout too? Sorting on next
update/forcast date could be interesting.
Is adding an Opengrib  files  downloader tabs make sense?

**Comment by did-g** [comment]
Today NAM Central America/West Indies  still download yesterday data and in my understanding there's no hourly step NOAA data is only 3 hours.
