### ISSUE TITLE
Are we ready for the next release?

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#144]
The main feature addition is the inclusion of regional models so I suggest that the next release number jump up from a "patch" to a "new feature" release and we can set it to ver. 1.2.0

Help in testing and digging up any embarrassing bugs is most welcome.

Any last minute suggestions are also OK

David

**Comment by dominiquehausser** [comment]
Perfect.
I'll do the update french part on opengribs.org ASAP.

**Comment by norulz** [comment]
I am not able to replicate the runtime warning.  Is it happening on Linux? Can you please give some more details.

Which NAM model had the problem and which parameter was showing bogus.
There are empty (no values) areas in the SW and SE and NE, NW due to the conversion of the Lambert projection to lat/lon.

**Comment by norulz** [comment]
Found and fixed the runtime warning. Looks like some unneeded code got pasted in the wrong place. The server status dialog does not use "downloadProgress"

**Comment by did-g** [comment]
Hi,
Yes there's missing values but Xygrib is rendering a spurious isoline on
the edge, MSL, temperature, whatever .

**Comment by norulz** [comment]
The only solution is to crop the entire data set inside this border artifact.
I suggest leaving it.

**Comment by norulz** [comment]
..mmmmm OK.....
I'ts an XyGrib issue the edge artifacts don't appear in Panoply or in openCPN grib plugin.

Any idea on how to fix it?

**Comment by norulz** [comment]
The modified code for openCPN seems to have fixed this issue.
[https://github.com/nohal/grib2_pi/blob/master/src/IsoLine2.cpp](https://github.com/nohal/grib2_pi/blob/master/src/IsoLine2.cpp)

I've seen this issue before when lambert conical is projected to lat/lon

**Comment by dominiquehausser** [comment]
Very nice fix
