### ISSUE TITLE
Area selection for download needs minimum size enforcement

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#151]
Now that we added decimals to the degrees defining the rectangle it is possible to select an area that is small enough not to have a grid data point in it. The Grib Sever fails and returns "Bad Request".

Min size enforcement is needed.

**Comment by norulz** [comment]
Fixed in v1.2.2

**Comment by norulz** [comment]
This still appears to be an issue

**Comment by did-g** [comment]
Hi,
Have you any area size sample showing this issue?

Didier

**Comment by norulz** [comment]
Hi Didier,
Here is the example that was posted in the support forum. Less than one degree in both axes. When the lat-lon numbers are rounded up to 1x1 degree a result is retreived.

David

![image](https://user-images.githubusercontent.com/6072089/67204598-84718200-f416-11e9-8fc5-12b8f5bc83f1.png)

**Comment by did-g** [comment]
Hi,
Seems to me it could be a bug on the server side, xygirb request is:
GET
/getmygribs2.php?osys=ubuntu&ver=1.2.7&model=arome_p025_&la1=43&la2=43.75&lo1=5&lo2=5.75&intv=1&days=1&cyc=last&par=W;p;R;C;T;H;G;&wmdl=none&wpar=
HTTP/1.1

**Comment by norulz** [comment]
You were correct. The server side was casting la1, la2... to int instead of float. At an earlier stage we were only using integers for the rectangle and I didn't update the servers side when we made the change.

It is now possible to request a rectangle less that one full degree.
Thanks.
