### ISSUE TITLE
ICON-EU cloud issue on every second time step

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#154]
@did-g hi,

A user is having an interesting issue with clouds. See post on forum at [opengribs forum](https://opengribs.org/en/forum/xygrib-support/59-icon-cloud-isseu?start=12#281)

I downloaded the grib file that he provided and it looks perfect. I'm unable to replicate the problem of most of the cloud data vanishing on every second time step.

Do you have an idea what the issue might be?

**Comment by dominiquehausser** [comment]
Unable to replicate the problem either.

**Comment by norulz** [comment]
@did-g The problem is solved. Great intuition!
