### ISSUE TITLE
How should we display Gusts?

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#161]
If we add a weather display option for gusts what would be the desired display.
This considering that gust values do not include direction. 
Also consideration needs to be given that gust contour shading combined with wind barbs might be a bit confusing.

**Comment by dominiquehausser** [comment]
I am not completly conviced with a graphical presentation of gusts (see wind - https://www.windy.com/?2018-12-17-09,45.829,-26.104,4,i:pressure and gusts - https://www.windy.com/fr/-Rafales-gust?gust,2018-12-17-09,45.829,-26.104,4,i:pressure.
The 2 main reason are : 
1. Wind speed in grib files is generally underestimated of 10-20%, which already imply a certain reflexion to interpret the data.
2. Gusts estimation in models is probably not precise, I have read a couple of papers concluding that gusts data are to be taken very carefully, And you know that with light winds, gusts values can even be lower.
So with graphical presentation, the risk of influencing the user is probably greater than only with numbers.

**Comment by MennoTammens** [comment]
Some models (e.g. [Harmonie](http://projects.knmi.nl/datacentrum/catalogus/catalogus/content/nl-nwp-harm-grid-p1.htm)) do have a direction with gusts:

Abbr. | Description | Code | Level | units
-- | -- | -- | -- | --
UWG | U-component of max wind gusts | 162 | 10 | m s-1
VWG | V-component of max wind gusts | 163 | 10 | m s-1

**Comment by did-g** [comment]
Hi,
Yep it's unclear if grib gust is really useful but xygrib could overlay
speed difference vs wind with it's own color scale, IMO when sailing it's
really what matter.

**Comment by norulz** [comment]
I feel that max gust speed is what we relate most to. I think that most users will first consult the view of wind data taking not of both force and direction. Next they are most likely interested to what the max wind force might be and will need to see gust force values. Currently we show these at points in the data board and in the meteotable and are missing and area display of gusts.

The attached GRADS images for wind and then for gust (force values without arrows) is perhaps a sample of what we should be showing. The would need a weather display option for gusts which should show both color contours and numeric values but no arrows. The current wind display can perhaps also have an option for the numeric value of wind force.

![image](https://user-images.githubusercontent.com/6072089/50164051-61ec7500-02ea-11e9-9098-fef7e3f5e70e.png)

![image](https://user-images.githubusercontent.com/6072089/50164071-6c0e7380-02ea-11e9-9d33-021bf487a169.png)

**Comment by rgleason** [comment]
This is a good idea. Shows the approximate magnitude, locations and occurrences, which is helpful. 
What is the letter designation?
Use a center point to circumference line to show direction if it is available?

**Comment by norulz** [comment]
Hi Rick,
The letters designate the sailing courses in the recent sailing championships held at Enoshima, Japan.
David

**Comment by rgleason** [comment]
Sorry, I guess it is the fields of color. Silly mistake.

**Comment by did-g** [comment]
Hi,
cf Gust overlay #164
![capture d ecran_2018-12-26_12-28-35](https://user-images.githubusercontent.com/12138026/50444627-d9815c00-0909-11e9-80a6-ede054eaf5db.png)

**Comment by caesar** [comment]
Re whether or not gusts are useful – in Patagonia we've found them to be much more accurate than the wind speed forecast in some places. In Puerto Natales for example the wind speed is always forecast as around 5-10 knots, but the gust forecast sows the true wind speeds of eg 30-60 knots.

**Comment by norulz** [comment]
Hi @caesar,
We are currently considering whether to show gusts as a delta value above the steady wind speed or to show the absolute gust values or to have a separate display for each.

The delta values help show areas of high turbulence but sailing yachts and other vessels are more interested in the maximum wind (or gusts) that they may encounter.

**Comment by norulz** [comment]
Feature added and ready for release.
Thanks to all
