### ISSUE TITLE
Suggestion for versioning

### ISSUE THREAD

**Issue by dominiquehausser** [opengribs/XyGrib#169]
Hello,

I have a suggestion for the versioning (may be it's only help me) :

starting from the publish version 1.2.0
"minor" evolutions
- odd number like 1.2.1.x for developing version (no need to change the value of x each time a new commit is done, but may be only when a "major" or considered as "major" by David is done).
- even number like 1.2.2.0 for published version (and may be 1.2.2.x for small bug correction of a publish version)

"major* evolution
- odd numbers 1.3.x for developing version (I am not sure it is easy to know in advance it will be a major change)
- even numbers 1.4.0 (a decision taken just before publication on opengribs.org)

Have a nice day

**Comment by norulz** [comment]
Hi,

Your suggestion makes sense but our setup (CMake) deals with 3 digit version and I would like to stay with 3 digits.
I agree that we can release on even patches (3rd digit) and while doing development work use odd patch numbers. 
For larger functional jumps I suggest in only advancing the 2nd digit by 1. While working on a functional jump we can just run the patch digit up to 9 after the older 2nd digit and then advance on release.

**Comment by nohal** [comment]
Adding a 4th component to the version number in the CMake build infrastructure is quite trivial, if decided to do so.

**Comment by norulz** [comment]
More concerned about my brain overloading with a fourth version digit :-)

**Comment by dominiquehausser** [comment]
So, if I understand well :+1: 
1.20 release published
1.2.1 development release
1.2.2 updated release
1.3.0 major update
2.0.0 super major change

That's perfectly nice for my old brain

**Comment by norulz** [comment]
1.2.0 release published
1.2.1 development release
1.2.2 updated release
**1.2.9 development version for major update**
1.3.0 major update
2.0.0 super major change

👍 👍 ...but really - anything goes
