### ISSUE TITLE
Add Meteo France regional models to downloader subsetter

### ISSUE THREAD

**Issue by did-g** [opengribs/XyGrib#173]
Hi,

MF publishes 0.025 regional gribs but IMO they are too big for downloading them as a whole:
  Indien-20190109-00.grb2  242M 
  Polynesie-20190109-00.grb2  53M 
  N-Caledonie-20190109-00.grb2  39M
  Antilles-20190109-00.grb2 64M 
(I don't have Guyane)
What about adding them to opengrib subsetter?

There's also 
https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=259&id_rubrique=42
24 run a day 15mn step, but there's fees, setup and download, no license fee though. 
I haven't ask them but in my understanding it'd be expensive. 
Maybe a deal with one of their users?

**Comment by norulz** [comment]
The volumes to deal with are prohibitive with current server resources. Handling of regional models at medium resolution is the limit for subsetting right now.

I think that the best solution for hires regional models ( < 4km ) is to prepare a mosaic of pre-cut gribs such as offered on OpenSkiron for openWRF and COSMO-DE.

Even to prepare pre-cuts for MF 0.025 output will be a challenge with MF's public download facility. The EU law forces them to make output available but it does not define at what bandwidth and load conditions. As you mentioned, they do offer a premium download facility for a fat fee.

I will set up  a test to produce pre-cuts and to also check the subset possibility for this stuff.

This leads to a feature that is on my mind - **"Integral pre-cut grib download in XyGrib"**. I suggest to start throwing around some ideas on how best to do this.

**Comment by did-g** [comment]
Let me know which ones you want to pre-cuts, I already have AROME 0.025 and
0.01 , 00H, 03H, 06H, 12H and 18H + OM SP1 and SP2.
I'll put them somewhere.

**Comment by dominiquehausser** [comment]
I had about 1 year mail exchange with MeteoFrance to try to have a better bandwidth to dowload their AROME, Arpège grib files.
They just gave me the standard URL to download the files. Terribly slow and most of the time you get a message : "Reessayer...". With a script it could take easily half a day.
@did-g : May be you have a better result with your request, to allow to produce the pre-cut files in a reasonable time.
As I go next week to Polynesia, I am very interested to see Polynesie-20190109-00.grb2 ;-)

**Comment by did-g** [comment]
You can get them at:

http://176.31.74.196/

http://176.31.74.196/HD
availability time in UTC roughly 30 mn to 1 hour after they are fully
available on MF site.

**Comment by dominiquehausser** [comment]
Thanks.

**Comment by dominiquehausser** [comment]
@did-g : Do you intend to produce regularly the grib files on http://176.31.74.196/HD and http://176.31.74.196/OPENGRIBS ?
If yes, do you agree that we mention them on https://opengribs.org/fr/gribs-fr (english and french of course) ?

**Comment by norulz** [comment]
Arome 0.025 deg is implemented and committed.
Please try it out and see if there are any issues.

**Comment by did-g** [comment]
Hi
No rain but you can select it.
On linux resolution dropmenu is too small if the dialog box isn't open with
AROME 0.025 selected by default the first time.

**Comment by norulz** [comment]
I'll fix these.
I did use cbModel->setMaxItems(15) as the default is 10 and we have 11 items in the cb.
In windows there is not a problem after the above setting. I wonder why it did not fix it for linux.

**Comment by norulz** [comment]
Tried it in Ubuntu 18.04 and the cb does not hide Arome. All items are visible when the cb is clicked open.

**Comment by norulz** [comment]
![image](https://user-images.githubusercontent.com/6072089/51091676-81b27400-1796-11e9-89b4-16f40c0be5f0.png)

**Comment by did-g** [comment]
My apologies I wasn't clear, it's the resolution pull down the problem.
How to reproduce:
Start Xygrib
select Arpege
exit Xygrib
Start Xygrib
Select Arome 0.025
Resolution 0.025 is selected but only 0.02 and half of 5 is visible.


BTW you could fine tune your download time AROME 0.025 is already available
at 22h50 GMT

**Comment by did-g** [comment]
On Sun, Jan 13, 2019 at 8:14 AM Dominique Hausser <notifications@github.com>
wrote:

> @did-g <https://github.com/did-g> : Do you intend to produce regularly
> the grib files on http://176.31.74.196/HD and
> http://176.31.74.196/OPENGRIBS ?
>
As long the server last (not always at the same IP but it's up since mid
2015)

> If yes, do you agree that we mention them on
> https://opengribs.org/fr/gribs-fr (english and french of course) ?
>
Need some kind of dns (IP isn't stable) and I have to double check with
IFREMER or remove current data first.

**Comment by dominiquehausser** [comment]
@did-g OK, I'll wait a green light to add the info

**Comment by did-g** [comment]
Hi,
rain is ok, but can't download 2019-01-14 06H run, tried at 11H UTC
it looks like process stopped too early (10h19 UTC) but latest files were
only available around 10h40 UTC

**Comment by norulz** [comment]
The precipitation issue was a server side issue - fixed

Resolution combo width issue is also fixed.

> BTW you could fine tune your download time AROME 0.025 is already available at 22h50 GMT

I find that every Jack Robinson and his uncle are trying to download as close as they can to the release time. It works much better about 40 minutes later

**Comment by norulz** [comment]
> rain is ok, but can't download 2019-01-14 06H run, tried at 11H UTC it looks like process stopped too early (10h19 UTC) but latest files were only available around 10h40 UTC

I messed with the cron time settings yesterday and obviously set them too early. (Arpege-EU as well).
I'll make adjustments.

**Comment by norulz** [comment]
Implemented
