### ISSUE TITLE
issue with showGribGrid

### ISSUE THREAD

**Issue by did-g** [opengribs/XyGrib#175]
Hi,
Two things with Show Grib 
- show grib grid is only displayed if there's also an overlay, from reading the code it could be a bug or the  menu entry should be greyed if there's no overlay displayed.

- there's only one grib grid displayed but with current and wave grib have 3, as a matter of fact a grib could have as many grid as records.

Should we display more than one grib grid? Or keep only the grid for displayed overlay? In this case should we add one on arrows when displayed on grid if they are displayed on grid (wave can't)?

If we only display grid for the visible overlay should we remove points with no data?

Personally I'm for:
- displaying grib grid for the rendered overlay so grey the option if there's no overlay selected.
- adding a 'wave display on grib grid' entry in sea menu.
- only display grid point if there's data, it's what we'll get with no regular grids anyway.

**Comment by dominiquehausser** [comment]
A small user input:
As the resolution of grib file as increased, I nearly do not use any more the option "Show Grid grid" (to avoid a black image ;-)
![capture d ecran de 2019-01-10 12-17-16](https://user-images.githubusercontent.com/38014738/50965232-b2ae5280-14d1-11e9-9782-bf82378d4820.png)

I use normally when I zoom a lot on a small area (or if the resolution is low) the "Wind arrow on Grib grid" to get a better idea of the potential interpolation between 2 data given in the Grib file.

Question is : does this option  "Show Grid grid" really still bring an info or is it enough to have "Data arrow on Grib grid", saying data to be able to have not only the wind arrow, but also wave and current arrow on Grib grid.

Concerning Weather map and Sea (that we could rename Sea map), it is an historical separation into 2 menus. I never really understood why, probably to avoid a so long menu, that it does not fit anymore on the screen.

We could certainly have a reflection on the ergonomics of the menus (specifically this 2 that are used the most.
That is also probably why "Weather options" / "options présentation graphique" is a submenu of Weather map, even if in the beginning I was a bit disturb to have some element there and other under the menu "Options".

**Comment by did-g** [comment]
Hi,
Yep it's an issue  with arrows on grid option too.
I made a PR #178 for testing.

Another stuff would be to remove arrow on grid while keeping 'Numerical interpolation'
If 'Numerical ...' is not set and there's enough room for displaying arrows on grid layout do it.

Yep menus layout is a bit random.

**Comment by norulz** [comment]
completed
