### ISSUE TITLE
Feature request - allow reading NetCDF files

### ISSUE THREAD

**Issue by simon-msl** [opengribs/XyGrib#18]
Have you ever considered this ?
This is a format that is widely used in the meteo/ocean forecasting world, including a wide range of very high quality, open-source datasets, notably high-res waves and currents. It would open up a lot of opportunities in terms of which data can be visualized.
Happy to help / provide more infos if needed.

**Comment by norulz** [comment]
Not really. Grib is the WMO standard for meteorology data and it does not appear to be changing.
Gribs are by far, much more efficient in space and speed than NetCDF files.

I am aware of the fact that many good ocean resources for waves and currents are in NetCDF format. It is very simple to convert these to Grib format for distribution and use thus making everyone's life much easier (a factor of 50 in size for instance). OpenSkiron.org does this for the openWRF gribs.

**Comment by norulz** [comment]
Try Iris http://scitools.org.uk/iris/docs/latest/index.html. I haven't tried it but it looks interesting

Alternately use the CDO utilities and script a converter yourself. This is what I use to convert hi-res current data from Netcdf to grib.   http://computing.io/wp/2013/11/converting-netcdf-to-grib/

Which specific data are you interested in converting?

**Comment by simon-msl** [comment]
Thanks, 
CDO is a great tool, and indeed quite straightforward to convert so I'll just do that.
 I was interested in the wind and current data that is available via https://marc.ifremer.fr/ - very high res data for the french coast.
