### ISSUE TITLE
QGIS integration

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#180]
As @dominiquehausser suggested the discussion on grib download in QGIS should continue here.

XyGrib does not expose an API.

The download logic can be found in DialogLoadGRIB.cpp and in FileLoaderGRIB.cpp.
I can provide an API document and some instructions as to the server side API.
We do not expose the server side code. It is not licensed GPL.

Similar integration has been done for qtVlm and is planned at least for the grib plugin in openCPN

**Comment by norulz** [comment]
Hi @pcav ,
Does QGIS currently have the ability to display weather data in grib format?
Do you have an idea on the number of QGIS users who use grib files?
David

**Comment by pcav** [comment]
Yes, see example attached
![grib11](https://user-images.githubusercontent.com/691842/51549410-ac718c00-1e6a-11e9-82fb-70067df66ebf.png)

**Comment by dominiquehausser** [comment]
I am sure too that the potential could be quite important.

A survey among QGIS user will definitly give the reasons and the size of interest (and help to find people to help).

Prevention of weather events at relatively small scale in areas not very well covered by weather alert system, as found in the large countries with well equiped met offices (these are also the QGIS users instead of a very expensive commercial one.

The next question certainly will be : How many requests the server will accept, whithout being overloaded ?

**Comment by dominiquehausser** [comment]
I may be in trouble to setup a questionnaire and to follow it, as I will spent most of my time at sea with very low bandwith the next 6 months, but I will try to suggest a couple (not more than 10, with room for comments) of questions before 15/02, if @norulz think it is a good idea to do it to take a decision to have a closer interaction with QGIS, including collaboration of QGIS team to XyGrib project.

**Comment by pcav** [comment]
Please let me know if I can be of help. We have regular polls among QGIS users, no problem in setting up one. Maybe it makes sense to ask both XyGrib and QGIS users.

**Comment by norulz** [comment]
As I see it, the new demand for grib files that will be generated by the new grib reading feature in QGIS will add some demand to the openGribs.org grib server even without an internal grib downloader. Users will simply use XyGrib as a tool to download files for opening in QGIS. 

Having an integrated download facility may increase the specific demand for openGribs.org supplied gribs as they will be easier to obtain than other grib files. We are currently seeing just over 300 requests in a 24hr period and the current server has quite a bit of growth available.

The server logs will show the integrated QGIS requests and I do not predict that we will have very much increase in traffic. If we do we can decide at that time on how to increase server capability.

As for joining the QGIS project - of our three contributors, one is crossing the Pacific backwards, one is trying to get a doctoral thesis started and the third is doing most of the work :-). We are happy to share the grib server resource with other open source end users and I can help with the server interface. For this please contact me by email

David

**Comment by pcav** [comment]
But I think we need a clean solution for this issue.

**Comment by pcav** [comment]
Hi all, any news on this? I'd be willing to give a hand. We'll have our biannual hackfest soon, and this could be a good occasion to work on this.

**Comment by norulz** [comment]
Hi Paolo,
My understanding was that the ball is in your court and that you would be implementing server requests to opengribs.org in the QGIS weather element. Did you not receive the API details to interface with the grib server?
David

**Comment by pcav** [comment]
OK, I can go ahead on the QGIS side. I suggest you to consider joining forces: I believe your work would perfectly integrate with QGIS, providing a more complete user experience, and attracting tons of new users, and potentially contributors.

**Comment by pcav** [comment]
You can follow the thread here: 
https://lists.osgeo.org/pipermail/qgis-developer/2019-February/056248.html

**Comment by norulz** [comment]
I fully support your idea and welcome the added outreach of the grib data. I, personally, am too tied up with other activities to be able to contribute more than answering questions on the interface.

Other contributors here are, of course, free to do as they please.

**Comment by pcav** [comment]
OK, will keep you updated on this ticket.

**Comment by pcav** [comment]
First steps: https://gitlab.com/faunalia/gribdownloader
Feedback greatly appreciated.
Thanks a lot for allowing us.

**Comment by pcav** [comment]
First steps: https://gitlab.com/faunalia/gribdownloader
Feedback greatly appreciated.
Thanks a lot for allowing us.
