### ISSUE TITLE
Portable Version of XyGrib

### ISSUE THREAD

**Issue by free-x** [opengribs/XyGrib#182]
Hi,

would it be possible to create a portable version of XyGrib? I don't always have my Linux with me and some skippers don't allow me to fiddle with their Windows laptops. So my question is whether it would be possible to compile such a version and provide an archive like zyGrib did before. Just unpack a ZIP on the USB-Stick, where everything you need to start and use XyGrib is inside.

Regards
free-x

**Comment by norulz** [comment]
Hi,
If you copy the contents of the XyGrib installation folder on Windows to a USB stick and then also add the 'data' folder tree (found in \users\<user>\AppData\Roaming\openGribs\XyGrib\).
This should work.
Note that if it is run on a machine that has an XyGrib installed the application will run on the USB stick but it will access the existing 'data' folder tree on the HD.

David
