### ISSUE TITLE
problem open grib file

### ISSUE THREAD

**Issue by ciacio3830** [opengribs/XyGrib#186]
Hi,
I converted the output of wrf-arw to grib v2, but I get the error in the opening. Can anyone help me? 
I attach my grib output
thanks
[output.zip](https://github.com/opengribs/XyGrib/files/2809770/output.zip)

**Comment by norulz** [comment]
Hi,
The grib files are produced with Lambert Conformal Projection and XyGrib does not handle this projection. 
Try creating the domain with lat-lon projection.

David

**Comment by norulz** [comment]
Not an issue. Closing.
