### ISSUE TITLE
Handling of ECMWF ERA5 reanalysis data sets - what is the best way to implement?

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#193]
Hi to all,

ERA5 reanalysis data is openly available for research etc and provides grib v1 files
The data uses ECMWF grib definition table 128 for atmospheric data and table 140 for wave data.
XyGrib does not currently handle these grib tables and all fields of the data are unrecognised.

My question is: "how should we implement such reanalysis data sets with ECMWF grib tables?"

My initial observation is that there are two routes:
1. We implement addition table sets for the existing parameters (grib def table 2).
2. We catch and translate the ECMWF record dataType to our current dataType's on the fly during the grib read.

Are there more options?
Grib file attached
David

[onehour.zip](https://github.com/opengribs/XyGrib/files/2871814/onehour.zip)

**Comment by dominiquehausser** [comment]
I have to check what are really those data. It seems to be "historical" data presenting past events in more details.
The question is probably also to see if ERA5 has some interest of usin XyGrib.

**Comment by norulz** [comment]
Look up Copernicus ERA5 on Google and you will find the interface. One needs to register.
There is interactive download or scripted download.
Of course it is all reanalysis (historic) data that is useful for research and teaching. There are many parameters but no geographic sub-setting. You get the  whole world.

**Comment by did-g** [comment]
I'd say 2)     

> 2\. We catch and translate the ECMWF record dataType to our current dataType's 

but with a different DataCenterModel, anyway level stored seem wrong, wind level 0 for 10m and so on.

**Comment by norulz** [comment]
I agree on option 2.
The trigger for translation might better be 'table2Version' rather than 'dataCenterModel' (Section_1 byte 4)
I'm not sure if the reader provides table2Version. I'll check later today.

**Comment by norulz** [comment]
Here is a sample ERA5 grib with the most common fields
[era5_sample.zip](https://github.com/opengribs/XyGrib/files/2883616/era5_sample.zip)

**Comment by norulz** [comment]
Handled in 1.2.6

**Comment by dominiquehausser** [comment]
The only set of data I have been able to visualise with XyGrib are coming from ERA5 hourly data on single levels from 1979 to present.

I tried ERA5 hourly data on pressure levels from 1979 to present but I have an error message File cannot be open (I took similar data at a known pressure level like 850 hPa).

Does it mean that the adaptation was only done for the first set of data ?

**Comment by norulz** [comment]
You are right. Only single level data is working and not the pressure level stuff.
Sample grib attached.

@did-g Hi, is it a big deal to add the pressure level data?

[adaptor.mars.internal-1562077091.195884-15467-19-02c0f761-b13c-4362-a442-aff71ba41c48.grib.zip](https://github.com/opengribs/XyGrib/files/3350492/adaptor.mars.internal-1562077091.195884-15467-19-02c0f761-b13c-4362-a442-aff71ba41c48.grib.zip)

**Comment by norulz** [comment]
Hi @dominiquehausser @did-g 
I've already made the change for:
wind, relative humidity, temp, geopotential height.
Is anything else required?

**Comment by did-g** [comment]
Hi

It doesn't seem we are able to display other ERA5 variables anyway.

Error is trivial but 129 is geopotential, shouldn't *0.102 (Aka 1/9.8)
better than 0.1?


Regards
Didier

**Comment by norulz** [comment]
You are right! I'll change it.
