### ISSUE TITLE
Updating zygrib

### ISSUE THREAD

**Issue by rgleason** [opengribs/XyGrib#195]
I have version 7 from 2015. How do I update?
Where is the maintenance installer?
zygrib does not seem to follow normal Windows installation routines.
Your maintenance installer wiki does not show where to find it.
Thanks for the great program.

**Comment by nohal** [comment]
Zygrib never had an installer, simply delete it.
XyGrib installers are at https://opengribs.org/en/downloads

**Comment by rgleason** [comment]
Thanks Pavel.
