### ISSUE TITLE
CAPE map not drawing with ICON_EU gribs

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#199]
User reported this. 
Works ok with pre-cut gribs from OpenSkiron

**Comment by did-g** [comment]
Hi,
Look like the server isn't returning data for CAPE, request CAPE alone:

> GET
> /getmygribs2.php?osys=ubuntu&ver=1.2.5&model=icon_eu_p06_&la1=48.92&la2=51&lo1=-3.88&lo2=-0.82&intv=12&days=1&cyc=last&par=c;&wmdl=none&wpar=
> HTTP/1.1
> User-Agent: XyGrib_unx/1.2.5
> Connection: Keep-Alive
> Accept-Encoding: gzip, deflate
> Accept-Language: fr-FR,en,*
> Host: grbsrv.opengribs.org
> HTTP/1.1 200 OK
> Date: Tue, 05 Mar 2019 20:06:27 GMT
> Server: Apache/2.4.18 (Ubuntu)
> Content-Length: 43
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json
> {"status":false,"message":"Request failed"}
>

Same with MSL

> GET
> /getmygribs2.php?osys=ubuntu&ver=1.2.5&model=icon_eu_p06_&la1=48.92&la2=51&lo1=-3.88&lo2=-0.82&intv=12&days=1&cyc=last&par=P;c;&wmdl=none&wpar=
> HTTP/1.1
> User-Agent: XyGrib_unx/1.2.5
> Connection: Keep-Alive
> Accept-Encoding: gzip, deflate
> Accept-Language: fr-FR,en,*
> Host: grbsrv.opengribs.org
> s0%HTTP/1.1 200 OK
> Date: Tue, 05 Mar 2019 20:06:45 GMT
> Server: Apache/2.4.18 (Ubuntu)
> Content-Length: 188
> Keep-Alive: timeout=5, max=100
> Connection: Keep-Alive
> Content-Type: application/json
> {"status":true,"message":{"url":"http:\/\/grbsrv.opengribs.org
> \/downloads\/1551816405604\/20190305_200645_ICON_EU_P06_.grb2","size":5425,"sha1":"6b79a069d5ef92dfde36c51f9decad1622f8b6b5"}}
>


But:

> grib_ls ~/grib/20190305_200645_ICON_EU_P06_.grb2
> edition      centre       date         dataType     gridType
> stepRange    typeOfLevel  level        shortName    packingType
> 2            edzw         20190305     fc           regular_ll
> 0            meanSea      0            prmsl
> grid_complex_spatial_differencing
> 2            edzw         20190305     fc           regular_ll
> 720          meanSea      0            prmsl
> grid_complex_spatial_differencing
> 2            edzw         20190305     fc           regular_ll
> 1440         meanSea      0            prmsl
> grid_complex_spatial_differencing
>

Only MSL, no CAPE.
Is 'c' the proper value for CAPE ?

**Comment by norulz** [comment]
Wow you are quick :-)
I was planning to looking into it on the weekend. I'll check the server and see if it was a one time problem or something needs fixing.

**Comment by norulz** [comment]
This has been fixed on the grib server
