### ISSUE TITLE
Feature request: Show low pressure system cold / warm fronts (Synoptic)

### ISSUE THREAD

**Issue by taruti** [opengribs/XyGrib#204]
I'd like to see cold/warm/occlusion fronts related to low pressure systems with XyGrib.

How should it be done, or is this outside the scope of XyGrib?

i.e. something like https://www.metoffice.gov.uk/weather/maps-and-charts/surface-pressure/

**Comment by norulz** [comment]
Hi,
This is something that the meteorologists still do manually based on several types of sources including sat images.
There are some efforts to automate drawing of fronts and if I remember correctly Meteo-Consult have computer driven marking of fronts
Right now this is a bit beyond the scope of XyGrib. If anyone comes by with a decent algorithm we will more than happy to integrate it.

BTW, displaying precipitation colour map and reflectivity (if it is in the grib data) both help in showing frontal systems on XyGrib as is.

David

**Comment by taruti** [comment]
Original ZyGrib supported IAC Fleetcode NOAA, so fetching synoptic charts could perhaps be possible?

**Comment by norulz** [comment]
Fetching weather fax files and other meteo images is something that has been considered for a future feature addition.

**Comment by dominiquehausser** [comment]
An indirect way to get front from models is to look at the 0° Isotherm. It is not perfect but can help...
