### ISSUE TITLE
Wave propagation direction ???

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#210]
Oceanographic standards state the wave direction (propagation) to be the direction TOWARDS which the wave is moving (opposite to the standard for wind direction).

This means that we have a bug in the reporting of wave direction in the meteotable and in the weather data board

**Comment by did-g** [comment]
Hi,

But meteorologists and mariners use from...
Maybe an option ?
At least add an unambiguous arrow in meteotable.

Thought?

**Comment by norulz** [comment]
"Modern Marine Weather" by David Burch says from.
ECMWF and Australian Weather Service say to.
NOAA doesn't say anything (They might but I couldn't find anything).
I'm happy to leave it as is.
Arrows in the meteotable is a good idea.

**Comment by norulz** [comment]
NOAA is also "from"
https://www.ndbc.noaa.gov/measdes.shtml
