### ISSUE TITLE
Windows static data files location problematic with special characters in user name

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#217]
XyGrib fails to find the data folder structure in the users home section if the user name has a special character  (which is used in the folder name).
This also occurs in some flavours of Linux if I'm not mistaken.
Some Qt string function probably needs to be applied.

**Comment by did-g** [comment]
Hi,
It's likely related to
760451c704e0b9165cf49b9af54322d1d5b6ba3a

but I'm afraid a proper solution has to replace C fopen IO with QFile, not a small change.

**Comment by norulz** [comment]
Changes made.
