### ISSUE TITLE
Fedora 28 broken dependencies

### ISSUE THREAD

**Issue by weleoka** [opengribs/XyGrib#229]
It seems the dependency on `https://pkgs.org/download/libproj.so.13` is not available on Fedora 28.

A tested package dependency list for XyGrib on Fedora 30 is available at https://gitlab.com/weleoka/xygrib-linux-dependencies

Solution: update INSTALL.md instructions to Fedora 30

**Comment by norulz** [comment]
Thanks!
Pull request has been merged.
David
