### ISSUE TITLE
Ubuntu 19.10 : Qt5LinguistToolsConfig.cmake and 2 other files missing

### ISSUE THREAD

**Issue by dominiquehausser** [opengribs/XyGrib#245]
I had a crash on my home PC (not very new), which push to reinstall from scratch and I decided to install the last Ubuntu version (19.10)

In folder /usr/lib/x86_64-linux-gnu/cmake qttools5-dev-tools do not install 
$ ls /usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/
Qt5LinguistToolsConfig.cmake
Qt5LinguistToolsMacros.cmake
Qt5LinguistToolsConfigVersion.cmake

I just copy them from my laptop (18.04) and it is OK, but I saw that in PR #235 there was a modification to suppress the call " FIND_PACKAGE(Qt5LinguistTools)"

I do not know what is the best for the future ?

**Comment by norulz** [comment]
Pavel added the language compilation to the entire build process when we converted to Cmake.
This is very useful in preparing our own releases in binary form.
For all those who prefer to build on their own or prepare packages for distros simply need to comment out the search for tools or the inclusion of the language folder in the Cmake project file.
I don't think that it is a good idea to have two Cmake project files.

**Comment by dominiquehausser** [comment]
If I understand well he CMakefile present in the folder data/tr (https://github.com/opengribs/XyGrib/blob/master/data/tr/CMakeLists.txt) could be removed.

**Comment by niclasr** [comment]
> If I understand well the CMakefile present in the folder data/tr (https://github.com/opengribs/XyGrib/blob/master/data/tr/CMakeLists.txt) could be removed.

It can't just really be removed as @norulz explains since it is used to generate the .qm files. But since the output of it is also put in the git repo it only has to be run when translations are updated, if I understand correctly.



> 
> 
> I had a crash on my home PC (not very new), which push to reinstall from scratch and I decided to install the last Ubuntu version (19.10)
> 
> In folder /usr/lib/x86_64-linux-gnu/cmake qttools5-dev-tools do not install
> $ ls /usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/
> Qt5LinguistToolsConfig.cmake
> Qt5LinguistToolsMacros.cmake
> Qt5LinguistToolsConfigVersion.cmake
> 
> I just copy them from my laptop (18.04) and it is OK, but I saw that in PR #235 there was a modification to suppress the call " FIND_PACKAGE(Qt5LinguistTools)"
> 
> I do not know what is the best for the future ?

The cmake files you are missing are in the ubuntu package [qt5tools-dev](https://packages.ubuntu.com/disco/amd64/qttools5-dev/filelist), install that and you should be fine. Perhaps this is something to put in INSTALL.md ?

**Comment by dominiquehausser** [comment]
qt5tools-dev (in ubuntu 19.10) is without the mentioned files that's why I was surprised and open this question.
The requested packages are mentioned in INSTALL.md
As I am trying to take care of translations, I normally manage to update of .ts and compile .qm files.

Anyway thanks for your response.

**Comment by niclasr** [comment]
qt5tools-dev is not qt5tools-dev-tools as mentioned in the first post.
qt5tools-dev-tools has the binaries like linguist while qt5tools-dev has header and cmake files, that what I get out from reading the file lists on the web for each package.

**Comment by dominiquehausser** [comment]
I will check as i thougt i installer both of them
