### ISSUE TITLE
Arch linux package available

### ISSUE THREAD

**Issue by gromain** [opengribs/XyGrib#247]
Not an issue, more an information, but for those interested, I created packages in the Arch User Repository of XyGrib.
Both latest stable 1.2.6 and latest git master are available (under package name xygrib and xygrib-git).

Just thought I'd let you know!

**Comment by gromain** [comment]
Can be seen [here](https://aur.archlinux.org/packages/xygrib/) and [here](https://aur.archlinux.org/packages/xygrib/)

**Comment by gromain** [comment]
The high resolution maps package is now [available](https://aur.archlinux.org/packages/xygrib-maps/).

**Comment by dominiquehausser** [comment]
Thanks.
Are you going to maintain this repository and include the future versions ?
If it is the case, I will add the info on the download page (https://opengribs.org/en/downloads) of opengribs.org

**Comment by gromain** [comment]
Yes absolutely!
I'm going to use this almost daily now, so I'll maintain it!

**Comment by dominiquehausser** [comment]
Availabilty of Arch Linux package mentionned on the Download page of opengribs.org.
Issue can be closed

**Comment by gromain** [comment]
Excellent! Thank you!
