### ISSUE TITLE
maps not available

### ISSUE THREAD

**Issue by poidl** [opengribs/XyGrib#254]
Hi, I installed version 1.2.6 on Linux by building from source.

No maps where available after `make install`, although the `data` folder was correctly (?) installed in the `XyGrib` folder which then contained 1) the executable and 2) the `data` folder.

After seeing this comment:

https://github.com/opengribs/XyGrib/issues/222#issuecomment-506639767

I tried copying the `data` folder to `~/.local/share/openGribs/XyGrib/`

and it worked perfectly. 

Regards, Stefan

**Comment by norulz** [comment]
Hi,
If you look in folder .config in your home directory you will find xyGrib.conf which can be edited.
The first key is appDataDir= which you can set to wherever you wish the data folders to be.
Enjoy
