### ISSUE TITLE
Primary wave arrows 

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#257]
Wave arrows for Primary Wave Direction are not been visualized.

**Comment by did-g** [comment]
Hi, 
Any sample data?

Regards.
Didier

**Comment by norulz** [comment]
Hi,
It looks like I already fixed this in 1.2.7. 
You can check it with the attached grib. No arrows in 1.2.6 but working in 1.2.7
I'm closing the issue
[20201230_190942_.grb.zip](https://github.com/opengribs/XyGrib/files/5755433/20201230_190942_.grb.zip)

**Comment by dominiquehausser** [comment]
I cannot see the arrows with version 1.2.7 compiled after #267
![Capture d’écran de 2020-12-30 23-06-01](https://user-images.githubusercontent.com/38014738/103383669-e423ec80-4af3-11eb-9697-13b3f2cdc3e2.png)
![Capture d’écran de 2020-12-30 23-09-51](https://user-images.githubusercontent.com/38014738/103383745-2fd69600-4af4-11eb-8761-9bc2e4e458bc.png)

**Comment by norulz** [comment]
Hi Dom,

I recompiled the latest fetch and the arrows for primary waves are working. See below.
![image](https://user-images.githubusercontent.com/6072089/103403059-917c1c00-4b57-11eb-845e-391dda9b9ec2.png)

**Comment by dominiquehausser** [comment]
So I do not understand. Attached Xygrib.err and Xygrib.std; may be you can find something.
[Xygrib.std.txt](https://github.com/opengribs/XyGrib/files/5757111/Xygrib.std.txt)
[Xygrib.err.txt](https://github.com/opengribs/XyGrib/files/5757112/Xygrib.err.txt)

**Comment by norulz** [comment]
Consider a clean fetch from the git and build from scratch.

**Comment by did-g** [comment]
Hi David

Are you sure you aren't using a locally patched version?
It doesn't work for me either. It looks like there's a copy and paste
typo, should be:
diff --git a/src/MapDrawer.cpp b/src/MapDrawer.cpp
index 4576b57d3..75e7a6b4b 100644
--- a/src/MapDrawer.cpp
+++ b/src/MapDrawer.cpp
@@ -389,7 +389,7 @@ void MapDrawer::draw_MeteoData_Gridded
                        hasWaveForArrows =
plotter->hasData(DataCode(GRB_WAV_DIR,LV_GND_SURF,0));
                        break;
                case GRB_PRV_WAV_PRIM:
-                       hasWaveForArrows =
plotter->hasData(DataCode(GRB_WAV_DIR,LV_GND_SURF,0));
+                       hasWaveForArrows =
plotter->hasData(DataCode(GRB_WAV_PRIM_DIR,LV_GND_SURF,0));
                        break;
                case GRB_PRV_WAV_SCDY:
                        hasWaveForArrows =
plotter->hasData(DataCode(GRB_WAV_SCDY_DIR,LV_GND_SURF,0));

**Comment by norulz** [comment]
Yes! It was a local fix.
I updated the git

**Comment by dominiquehausser** [comment]
![Capture d’écran de 2021-01-01 21-57-14](https://user-images.githubusercontent.com/38014738/103446114-59222e00-4c7c-11eb-8626-074e8afe33b0.png)
tiptop thanks
