### ISSUE TITLE
ubuntu package contains the wrong binary

### ISSUE THREAD

**Issue by farotherside** [opengribs/XyGrib#260]
hey all,

running Ubuntu 20.04, using the stock repository I have installed xygrib-1.2.6-1build2 for amd64. this package actually contains the binary for xygrib-1.2.5.

as a second bug, running the binary warns that there is a new version 1.2.6 available, and asks that I use the Xygrib Maintenance Tool from the Help menu to upgrade. there is no Xygrib Maintenance Tool in the help menu; that menu just contains 'Help', 'About Xygrib', 'Check for Updates' (which brings up the same popup saying there's an update available and to use the Xygrib Maintenance Tool), and 'About Qt'.

**Comment by norulz** [comment]
Hi,
You are trying to use a third party package for XyGrib in which the Maintenance Tool has been removed and it may not be the latest version. You may consider contacting the third party who prepared the package.
I suggest that you download our Linux installation package from here https://github.com/opengribs/XyGrib/releases. It is a different approach using the AppImage philosophy but it does work on all Linux distros and versions and saves us a lot of effort.
David

**Comment by dominiquehausser** [comment]
Hi,
If you look https://opengribs.org/en/downloads, you'll have all the info about the available packages including for Debian/Ubuntu distros.
Have a nice day

**Comment by farotherside** [comment]
thanks, I'll take it up with the Ubuntu package maintainers.
