### ISSUE TITLE
(Question) How is it possible that XyGrib can get 1-8/10 days forecast data from NOAA?

### ISSUE THREAD

**Issue by BirukTes** [opengribs/XyGrib#286]
Hello,

How is it possible that XyGrib can get 1-8/10 days forecast data from NOAA while only past subdirectory are shown, for example here:- [GFS NOAA](https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl)?

> Global Atmospheric models ([https://opengribs.org/en/gribs](https://opengribs.org/en/gribs))
           GFS - NOAA-GFS model - Resolutions: 0.25, 0.5, 1.0 deg - Cycles: 00, 06, 12, 18 UTC - Days: 1-10

Also:

> Global Wave Models ([https://opengribs.org/en/gribs](https://opengribs.org/en/gribs))
WW3 - NOAA-WW3 model (global without Mediterranean Sea) - Resolution: 0.5 deg - Cycles: 00, 06, 12, 18 UTC - Days: 1-8

Thank you.

**Comment by norulz** [comment]
The NOAA/NCEP sub-directories that you mention contain the forecast produced on the current day and historic forecasts 9 days back.
However, each of the  sub-directories you mention contains a forecast next 384 hours into the future. 
XyGrib only takes forecast data produced on the current date (00z, 06z, 12z and 18z) as the data comes available and it retrieves 240 hours of forecast (i.e. the next 10 days).
I hope this answers your question.
