### ISSUE TITLE
Fedora 35 problem with Off/Online Install 1.2.6

### ISSUE THREAD

**Issue by bitwisetech** [opengribs/XyGrib#287]
./XyGrib_Linux_Online_Installer_v1.2.6 
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve ERR_free_strings
QSslSocket: cannot resolve sk_new_null
QSslSocket: cannot resolve sk_push
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot resolve SSLeay_version
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function SSLv23_clien

This is on an upgrade from Fedora 33 to Fedora35 and I get the above result on three PC's, both using the Offline installer and the Online version.     Any hints appreciated, Tks

**Comment by norulz** [comment]
We are currently starting to get a new version out and will try and address this issue.
We may discontinue the "Installer" builds for Linux and focus on regular Linux packages with help of the distro communities.

**Comment by bitwisetech** [comment]
Thank You for the reply.  I know, from another project, that the Qt packages seem to be named differently according to linux distro but I've not found one that fixes this.  I'll try building from source
