### ISSUE TITLE
Grib2 File Support

### ISSUE THREAD

**Issue by 99bobster99** [opengribs/XyGrib#295]
Would it be possible for you to include GRIB2 file support?

I'd like to access these Canadian GRIB2 files (https://dd.weather.gc.ca/ensemble/geps/grib2/raw/00/048/) 

I played around with the GribView program and it does support this file format. It would be great if XyGrib did as well!!

Possible?

**Comment by norulz** [comment]
Hi,
XyGrib does already read grib2 files. The files you refer to are special gribs for ensemble model output. I suggest using regular grib files, e.g. https://dd.weather.gc.ca/model_gem_global/15km/grib2/lat_lon/00/000/

Here is a PRMSL file shown in XyGrib
![image](https://user-images.githubusercontent.com/6072089/177047035-4eee1a06-527b-4581-b99a-6f34268c509e.png)
