### ISSUE TITLE
 More pressure levels from ERA5 hourly data file (950 hPa, 975 hPa, 1000 hPa)

### ISSUE THREAD

**Issue by Giacominibus** [opengribs/XyGrib#299]
I apologize for the question Maybe I posted it in the wrong section.
Is it also possible to view the data for 700 hPa, 750 hPa, 775 hPa, 800 hPa, 825 hPa, 850 hPa, 875 hPa, 900 hPa, 925 hPa, 950 hPa, 975 hPa, 1000 hPa present in the GRIB file ERA5 hourly data on pressure levels from 1959 to present ?

Thank you

**Comment by issamlagha** [comment]
Hi, is it possible to add these features :
- more pressure levels to visualize, especially high tropospheric/stratospheric pressure levels (100, 70, 50, 30, 20, 10, etc.) hPa.
- more parameters, like vertical velocity, absolute and potential vorticity, etc. which are available in a simple GRIB file (e.g: NCEP GFS GRIB file; https://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.0p25.f003.shtml).
- the ability to draw isolines for any variables (e.g: Isotachs, Isallobars, Isohumes, Isohyets, etc.).
- the possibility to directly convert a NETCDF file to a GRIB file (e.g: WRF output).
- the possibility to create and visualize a new custom variable (e.g: fire index, climate indices, etc.) and add to/modify the GRIB file.
- the possibility to use google maps/street API, ESRI products, GIS datasets, etc. 

The meteorological community would be really grateful!

**Comment by norulz** [comment]
Hi,
There are currently no developers active in the project. Perhaps at a later date these suggestions might be considered.
