### ISSUE TITLE
Server Problem

### ISSUE THREAD

**Issue by theeko74** [opengribs/XyGrib#30]
Does anyone have this "Server Problem" issue with new Grib downloader?
I had no problem before this morning...

<img width="732" alt="capture d ecran 2018-06-08 a 10 28 34" src="https://user-images.githubusercontent.com/22415254/41147513-de383684-6b06-11e8-9bdb-ce1973f20abf.png">

**Comment by norulz** [comment]
Yes. I have been working on the server and left it in an error state.
Will be working on it this evening. Tomorrow it should be back online.

**Comment by norulz** [comment]
Server is working OK since last evening
