### ISSUE TITLE
Add new features 

### ISSUE THREAD

**Issue by issamlagha** [opengribs/XyGrib#303]
Hi, is it possible to add these features :

- more pressure levels to visualize, especially high tropospheric/stratospheric pressure levels (100, 70, 50, 30, 20, 10, etc.) hPa.
- more parameters, like vertical velocity, absolute and potential vorticity, etc. which are available in a simple GRIB file (e.g: NCEP GFS GRIB file; https://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.0p25.f003.shtml).
- the ability to draw isolines for any variables (e.g: Isotachs, Isallobars, Isohumes, Isohyets, etc.).
- the possibility to directly convert a NETCDF file to a GRIB file (e.g: WRF output).
- the possibility to create and visualize a new custom variable (e.g: fire index, climate indices, etc.) and add to/modify the GRIB file.
- the possibility to use google maps/street API, ESRI products, GIS datasets, etc.

The meteorological community would be really grateful!

**Comment by norulz** [comment]
Hi,
Great suggestions. However, there are currently no active developers in the project.
