### ISSUE TITLE
wish: please add Météo-France Arome HD

### ISSUE THREAD

**Issue by thonglorais** [opengribs/XyGrib#307]
The Météo-France Arome model has been switched from the older 0.025° resolution version to the high-definition (HD) version, which has a resolution of 0.01°. With this change, the domain of the model is larger, the resolution is better, however there are fewer parameters ([source](https://luckgrib.com/blog/2022/03/06/new-grib-models.html)).

It would be great if Météo-France Arome HD was added as source to the Download-GRIB section.

**Comment by norulz** [comment]
Unfortunately the load and volume impacts of HD data on the XyGrib grib server are too severe for our "shoestring" setup.

**Comment by thonglorais** [comment]
OK, understood, thanks a lot for such a quick answer!
