### ISSUE TITLE
automation 

### ISSUE THREAD

**Issue by propedeutique56** [opengribs/XyGrib#312]
It would be very helpful to be able to download automticaly, with a batch command, a "given location"  ( the user recording the longitudes/ latitudes of the opposit points of the map) .

Also, most of the opensource routing app use . grib files. Would it be possible to convert .grib2 files in .grib in Xygrib ?

Thanks

**Comment by norulz** [comment]
The grib server resources are very limited as the operation is non-commercial and voluntary based. Donations only partially cover server running expenses. Therefore, the grib server frowns on batch downloads that drain resources and will eventually block IP's that persist to batch download. 

Most routing apps can read both versions of GRIB (1 and 2) irrespective of what the file suffix says - grib, grb, grib2 or grb2, If needed there are some linux command line utilities that will convert from one GRIB version to the other.

**Comment by propedeutique56** [comment]
Thanks for your answer.
Unfortunatly, I am using Simsail which is a great routing software but
doesn't function with .grb2 .
Anyway, thanks for Xygrib wich is great!
Bye

**Comment by norulz** [comment]
I can suggest using openWRF GRIB files found at [openSkiron](https://openskiron.org).
They are GRIB v1 files.
