### ISSUE TITLE
Isobars are not shown (while selected on) and need to be re-selected to work

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#33]
On restart or on changing grib files the isobars are no longer shown although the menu selector shows them to be on.
Clicking the selector off and then on resets the isobars.

The issue my be related to setting and getting application settings.

Help is welcome!

**Comment by tsenga** [comment]
Is this still an issue? I can't replicate this from the master branch

**Comment by norulz** [comment]
Are  you on Windows?

**Comment by tsenga** [comment]
Mac

**Comment by norulz** [comment]
Hi, I am now able to replicate the problem both on Windows and on Ubuntu.

1. Download 2 gribs. One without Pressure (MSL) and one with.
2. Open the grib with PMSL and make sure that the isobars are showing (option selected in menu).
3. Open the second Grib without PMSL. Of course no isobars will be seen although the selector is set on.
4. Reopen the first Grib with PMSL and no isobars are seen until the selector is turned off and back on again.

**Comment by tsenga** [comment]
Thx. I have now replicated on Mac as well.

**Comment by norulz** [comment]
Fixed!
Thank you Andrew.
