### ISSUE TITLE
Difference in Arpege from MeteoFrance and XyGrib servers

### ISSUE THREAD

**Issue by theeko74** [opengribs/XyGrib#43]
Hi,
I noticed a difference in wind speed/direction between grib files from Arpege model generated from XyGrib's server and the one generated from MeteoFrance's server. It is not a big difference, the overall wind forecast is closed, but there is some difference from 20NM approximately. Any idea why, as it should come from the same source?

XyGrib's server:
<img width="1956" alt="capture d ecran 2018-06-18 a 23 12 53" src="https://user-images.githubusercontent.com/22415254/41562732-c83ff7f0-734d-11e8-8319-fb4b9df44a3d.png">

MeteoFrance's server:
<img width="1967" alt="capture d ecran 2018-06-18 a 23 14 22" src="https://user-images.githubusercontent.com/22415254/41562907-4efccc50-734e-11e8-9337-071443fa8e24.png">

Another point: MeteoFrance's Arpege use a resolution of 0,1° at maximum and we can only select 0,5° in XyGrib's downloader module. Any idea why?

**Comment by norulz** [comment]
Can you please post the 2 files for examination.
There should not be any difference. Are they both from the Global Arpege files at 0.5 deg or is the second file from the 0.1 deg local nest? You can check in the "Info" button.

The reason the Arpege 0.1 deg is not included yet is that first priority was to provide access to global models. Large scale regional models and local nests (Arpege 0.1 and ICON-EU) will come later.

David

**Comment by dominiquehausser** [comment]
I think the discussion about the models differences and differences in the output of models on different scale could take place on the forum of opengribs.org (https://opengribs.org/en/forum/gribs-models) as it has not a lot to do with the development of the tool and should have there a larger number of concerned and interested persons. And may be an expert in numerical weather models could find the time to answer these questions (even providing links on papers not too complex for non specialists like me that discuss these points.

I'll try to find some answers to this question within the next months and will put these on the forum.
But do not hesitate to reproduce your question there.

**Comment by norulz** [comment]
The two files are from DIFFERENT MODELS. One from Arpege Global at 0.5deg and the second from Arpege European Nest at 0.1 which is a separate calculation run done as a nest under the global model.

If there would not be differences then there would be a problem.
