### ISSUE TITLE
Plan to integrate Arome model in GRIB downloader

### ISSUE THREAD

**Issue by theeko74** [opengribs/XyGrib#44]
Hi,
Arome model from MeteoFrance has a resolution of 0,025° for 2 days and is very accurate, especially if you sail in Mediterranean sea. Is it plan to integrate this model in XyGrib's server and in grib downloader module?

**Comment by norulz** [comment]
Theeko hello,

The problem with high resolution regional models is the size of the data sets and the subsequent loads on the grib server. The concept of an on-the-fly grib server works well with Global or large area local models. The preferred method for using high resolution gribs is to distribute them "pre-cut and packaged" like the openWRF, SKIRON and ICON-EU gribs posted on openskiron.org.

The next step with the Grib Server will be to add large area local models at MEDIUM resolution such as ICON-EU and NOAA-NAM.
David

**Comment by theeko74** [comment]
You mean that the model is not available worldwide and in some area it will generate an empty grib file? If yes, we could simply add a dialog message in case of empty grib, and display boundaries of the regional model (lat, lon). I like to use regional model for sailing as they (most of the time) are sufficient for short navigation.

**Comment by dominiquehausser** [comment]
Arome is not a worldwild model and is limited around France (météo france) with a little extension around (http://www.wetterzentrale.de/en/topkarten.php?model=aro&time=3&lid=OP&h=0&tr=3) and Norway (Norwaygian met office) (http://www.wetterzentrale.de/en/topkarten.php?model=arn&time=3&lid=OP&h=0&tr=3).

**Comment by norulz** [comment]
Theeko, The limited area is not the issue. The grib down loader will in the future show the coverage of limited area models. The issue is the HUGE data sets of HIGH RESOLUTION local models. These are better distributed as pre-cut files for download
