### ISSUE TITLE
Third party build script should not install libraries in /usr

### ISSUE THREAD

**Issue by MennoTammens** [opengribs/XyGrib#47]
In the [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) (FHS) the directory **/usr** is for files managed by the distribution, user installed packages should go to **/usr/local/**.

For building XyGrib installing the packages isn't necessary, the build scripts can be adapted to look for them in the directory where they are build.

**Comment by norulz** [comment]
I agree.
If you can modify the build scripts for openjpeg and g2clib, I will take care of the bash file and the INSTALL file.

**Comment by norulz** [comment]
The include statement in the two grib2 header files should also be changed. Pls include that in your PR.

**Comment by norulz** [comment]
Menno good evening,

I modified the build file for g2clib to install to /usr/local/ (as it is the customized library).
No action is needed if we decide to keep this library customized.
