### ISSUE TITLE
Please don't put the AppImage into another archive

### ISSUE THREAD

**Issue by probonopd** [opengribs/XyGrib#54]
Please don't put the AppImage into another archive. 
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

Thanks.

**Comment by norulz** [comment]
Hi,
I agree in principle that there should not be an extra packing. However, currently XyGrib is dependent on having the folder 'data' and all its sub-folders in the root of the executive file. 
We do plan downstream to separate data from the executive as is common practice in all platforms. Even in this case some installation or packaging is required.

Do have a recommendation on how to distribute an AppImage that needs accessible data to be 'attached' to it?
David

**Comment by probonopd** [comment]
* If the data is read-only, put it _inside the AppImage_
* If the data is read-write,  put it _inside the AppImage_ and _copy it out_ to somewhere in `$HOME` upon first launch of the application (this can be done using a custom `AppRun` script)

Please let me know whether this works for you (or why it doesn't).

**Comment by norulz** [comment]
Thanks for the pointer. The data is in part read-write. I will try your recommendation prior to the next release. 
I am keeping this issue open.

**Comment by norulz** [comment]
We also need to remember that in addition to maps colors can be edited and that translation files need to be added by the user. This requires the ability to access and write to the folders

**Comment by dominiquehausser** [comment]
Right
which means to move data/color to $HOME/.xygrib (for the scale of parameters)
for maps I do not know where it is now.
for translations, it is not movable yet to the local folder, a job to be done or knowing that new translations will be available in the next version.
That's goes also in the direction of improving the structure to be able to separate app from data suggested by nohal about builds.

**Comment by norulz** [comment]
Hi @probonopd ,

We are still using AppImage in v1.1.1 to support running one common binary package on as many Linux distros as possible and it has lived up to expectations very well in testing on multiple distros

XyGrib does however require the installation of several components (one optional) that can't be part of the AppImage as they require user access and editing (gis files, language, files, color specs and maps). To support robust installation for this for the many end users (not always too computer savvy), we opted to use the Qt Installation Framework 3.0 including the Maintenance Tool that it provides for future updates of the application via online repository. This solution is common for all desktop platforms and this consistency and simplicity is important to us.

The XyGrib.AppImage is therefore part of the installation system payload and not a discreet component. I understand that this is not entirely inline with the philosophy behind AppImage, but the circumstances of deploying a somewhat complex application force us to take a small step aside from this philosopy to ensure that the AppImage ends up happily in /opt/XyGrib/ (in its natural form) and is fully integrated with the other components and the OS.

We hope to continue enjoying your support in using AppImage as an excellent deployment solution for Linux binaries.

David

**Comment by probonopd** [comment]
Thanks for your explanation David, and thanks for using AppImage.

Just for the sake of completeness,
* An AppImage should run from _all_ locations (including USB sticks, network shares and such), not just from `/opt`
* You could have a small wrapper script copy files that need "user access and editing" from the AppImage somewhere to the user's `$HOME` if they are not there yet, thus effectively making the AppImage standalone

But hey, your decision; I understand that cross-platform consistency is important to you. (A Mac .app would probably do the same thing.)

**Comment by norulz** [comment]
Thanks.
