### ISSUE TITLE
Precipitation accumulation issue in GFS gribs

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#56]
Normalization to 3hr accumulation instead of 0-3,0-6,.... appears now to have being applied twice. Once in the Grib server and once internally in grib_record translation method (or elsewhere).

Needs to be identified and fixed

**Comment by dominiquehausser** [comment]
I cannot easily see any periodicity along the 10 days

**Comment by norulz** [comment]
The GFS gribs are pre-processed on our server to normalize the "strange" NOAA accumulation from 0-3, 0-6, 6-9, 6-12..... to 0-3, 3-6, 6-9, 9-12.... 
Problem is that XyGrib's code is doing something similar and causing non-normalized distribution of the rain and we need to stop one of the two processes. What you can see on the series of forecast times is that suddenly there is on particular hour without any rain whereas 3 hours before (and later) there was plenty.

**Comment by did-g** [comment]
Hi,

Temporary workaround would be to use PRATE.

I think  I know what's missing, I'll to make a proper PR at least for common case when there's only one interval.

**Comment by dominiquehausser** [comment]
I think all work to have clean data (data ready for use) should be done at the level of the server, as the grib files coming from different providers are not strictly standardised, meaning that the treatment is not universal but related to one model and one provider.

This will help to have a client with the little number of exceptions; which ideally should be defined in one file to facilitate maintenance

**Comment by norulz** [comment]
Fixed
Thanks to @did-g
