### ISSUE TITLE
missing .desktop file

### ISSUE THREAD

**Issue by Millak** [opengribs/XyGrib#59]
Adding a XyGrib.desktop file would allow it to show up in menus and would increase OS integration.

**Comment by free-x** [comment]
Coming soon ;-)
https://github.com/free-x/XyGrib/blob/debian/debian/xygrib.desktop

**Comment by norulz** [comment]
Good idea. Thanks

**Comment by free-x** [comment]
@norulz have you Official Icon( xygrib.png) for this purpose? I'm using now for packaging old zygrib icon. 

Regards
free-x

**Comment by norulz** [comment]
in the data/img/ folder there is xyGrib_32.ico that works well with .desktop files.
