### ISSUE TITLE
App data and settings separated from executable folder - MAC testing needed

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#80]
Following discussion on the subject, separation has been implemented, however testing on Mac is needed.

The settings remain "dual action"  - both OS native and ini files. The location of the ini files follows the QStandardPaths class as to the location specific for the OS. If the ini files are not found there they are initialized at this location. Should this not be successful the second option is to use the application current directory tree if writable ( data/config/...). Should this fail too then the OS temp folder is used.

For app data a new setting has been added to store the location of app data. This is the first lookup which is verified. Should it not exist the first search location is based on QStandardPaths for writable storage (the colors and translation files need to be editable). If not found second option is for common area for app data (/user/local/shared/... or c:/Program Data/...). Next option is to look in the current directory. If app data is not found and error is returned and this needs to be implemented into a file system dialog to point to where the data is. (still TODO).

DBG messages to application output allow monitoring the above behavior.

Please check this implementation on as many setups as possible. Mac has not yet been tested

**Comment by dominiquehausser** [comment]
I compiled from the last commit (227) on my home PC (Ubuntu 17.10) which had a 3 month old version of XyGrib (1.0.1)with ini files in ~HOME/xygrib; new xygrib.ini files found in ~HOME/.config/openGribs/XyGrib

**Comment by norulz** [comment]
Hi,
This is about to change again :-) . To be compatible with older platforms I changed the QStandardPaths enum and the ini files are now initialized in $HOME/.congig
