### ISSUE TITLE
New instance is not working

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#96]
Invoking a new instance from the mainwindow menu is not working.
@did-g - could this be connected to recent changes?

**Comment by dominiquehausser** [comment]
I build from git hub (commit 290) and it work for me on ubuntu 17.10 (I did not try yet on 18.04 LTS)

**Comment by norulz** [comment]
mmm..... it's working on Linux but not on Windows

**Comment by norulz** [comment]
Fixed
