### ISSUE TITLE
Bug. The last used settings in the Grib download dialog are not persistent

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#97]
Download Grib Dialog does not retain the chosen settings between uses. It did before

**Comment by norulz** [comment]
@did-g hi,
Perhaps this is following the changes you made to reduce calls to save settings.

Is this intentional?
```
void Util::setSettings (const QHash <QString, QVariant> &h)
{
}
```

**Comment by norulz** [comment]
:)

**Comment by did-g** [comment]
cf #100

**Comment by dominiquehausser** [comment]
Interesting, this problem do not exit on my build version...

**Comment by dominiquehausser** [comment]
No it was before the fix. After the fix of no problem.

**Comment by norulz** [comment]
Fixed
